import { z } from "zod";

const envSchema = z.object({
  CLERK_PUBLISHABLE_KEY: z.string().min(1).optional(),
  CLERK_SECRET_KEY: z.string().min(1).optional(),
  R2_ACCOUNT_ID: z.string().min(1).optional(),
  R2_ACCESS_KEY_ID: z.string().min(1).optional(),
  R2_SECRET_ACCESS_KEY: z.string().min(1).optional(),
  R2_BUCKET_NAME: z.string().min(1).optional(),
  DATABASE_URL: z.string().min(1).optional(),
  REDIS_URL: z.string().min(1).optional(),
  CRON_SECRET: z.string().min(32).optional(),
  OPENAI_API_KEY: z.string().min(1).optional(),
  OPENAI_ADVISER_MODEL: z.string().min(1).optional(),
  OPENAI_IMPORT_PARSER_MODEL: z.string().min(1).optional(),
  OPENAI_IMPORT_PARSER_IMAGE_MODEL: z.string().min(1).optional(),
  OPENAI_IMPORT_PARSER_PDF_MODEL: z.string().min(1).optional(),
  OPENAI_IMPORT_PARSER_STRONG_MODEL: z.string().min(1).optional(),
  OPENAI_IMPORT_PARSER_OCR_MODEL: z.string().min(1).optional(),
  OPENAI_IMPORT_PARSER_PRIMARY: z.string().min(1).optional(),
  BRANKAS_ENV: z.enum(["sandbox", "live"]).optional(),
  BRANKAS_STATEMENT_API_KEY: z.string().min(1).optional(),
  BRANKAS_STATEMENT_WEBHOOK_SECRET: z.string().min(1).optional(),
  FINVERSE_ENABLED: z.enum(["true", "false"]).optional(),
  FINVERSE_MODE: z.enum(["test", "live"]).optional(),
  FINVERSE_CLIENT_ID: z.string().min(1).optional(),
  FINVERSE_CLIENT_SECRET: z.string().min(1).optional(),
  FINVERSE_REDIRECT_URI: z.string().url().optional(),
  FINVERSE_TOKEN_ENCRYPTION_KEY: z.string().min(1).optional(),
  PAYPAL_ENV: z.enum(["sandbox", "live"]).optional(),
  PAYPAL_CLIENT_ID: z.string().min(1).optional(),
  PAYPAL_CLIENT_SECRET: z.string().min(1).optional(),
  PAYPAL_WEBHOOK_ID: z.string().min(1).optional(),
  PAYPAL_MONTHLY_PLAN_ID: z.string().min(1).optional(),
  PAYPAL_ANNUAL_PLAN_ID: z.string().min(1).optional(),
  PAYPAL_PRO_PLAN_ID: z.string().min(1).optional(),
  PAYPAL_BUYER_COUNTRY: z.string().length(2).optional(),
  PADDLE_ENV: z.enum(["sandbox", "live"]).optional(),
  PADDLE_CLIENT_TOKEN: z.string().min(1).optional(),
  PADDLE_API_KEY: z.string().min(1).optional(),
  PADDLE_WEBHOOK_SECRET: z.string().min(1).optional(),
  PADDLE_PRODUCT_ID: z.string().min(1).optional(),
  PADDLE_MONTHLY_PRICE_ID: z.string().min(1).optional(),
  PADDLE_ANNUAL_PRICE_ID: z.string().min(1).optional(),
  ADMIN_USER_IDS: z.string().min(1).optional(),
  ADMIN_EMAILS: z.string().min(1).optional(),
  ADMIN_ONLY_USER_IDS: z.string().min(1).optional(),
  POSTHOG_PERSONAL_API_KEY: z.string().min(1).optional(),
  POSTHOG_PROJECT_ID: z.string().min(1).optional(),
  POSTHOG_APP_URL: z.string().url().optional(),
  STAGING_BASIC_AUTH_USERNAME: z.string().min(1).optional(),
  STAGING_BASIC_AUTH_PASSWORD: z.string().min(1).optional(),
  CLOVER_IMPORT_STORAGE_DIR: z.string().min(1).optional(),
  CLOVER_DEPLOYMENT_ENVIRONMENT: z.enum(["staging", "production"]).optional(),
  CLOVER_ENFORCE_ENVIRONMENT_ISOLATION: z.enum(["true", "false"]).optional(),
  CLOVER_EXPECTED_DATABASE_PROJECT_REF: z.string().min(1).optional(),
  CLOVER_EXPECTED_R2_BUCKET: z.string().min(1).optional(),
  CLOVER_FINVERSE_ENVIRONMENT_ISOLATED: z.enum(["true", "false"]).optional(),
  ZOHO_SMTP_USER: z.string().email().optional(),
  ZOHO_SMTP_PASSWORD: z.string().min(1).optional(),
  ZOHO_SMTP_HOST: z.string().min(1).optional(),
  ZOHO_SMTP_PORT: z.coerce.number().int().positive().optional(),
  CIRCLE_INVITATION_FROM: z.string().email().optional(),
});

export type AppEnv = z.infer<typeof envSchema>;

export const getEnv = (): AppEnv => envSchema.parse(process.env);
