import type { ContextEntry, RegionalParsingProfile } from "@/lib/context-corpus";

type Country = { code: string; region: string; currency: string };

const rail = (country: Country, id: string, aliases: string[], paymentRail: string, confidence = 82): ContextEntry => ({
  id: `${country.code.toLowerCase()}-${id}`,
  aliases,
  signalKind: "payment_rail",
  countryCode: country.code,
  regionCode: country.region,
  paymentRail,
  institutionType: "wallet",
  currency: country.currency,
  counterpartyType: "wallet",
  purposeHint: "transfer",
  confidence,
});

const bank = (country: Country, id: string, aliases: string[], confidence = 80): ContextEntry => ({
  id: `${country.code.toLowerCase()}-${id}`,
  aliases,
  signalKind: "institution",
  countryCode: country.code,
  regionCode: country.region,
  institutionType: "bank",
  currency: country.currency,
  counterpartyType: "financial_institution",
  confidence,
});

const merchant = (
  country: Country,
  id: string,
  aliases: string[],
  categoryHint: string,
  purposeHint: NonNullable<ContextEntry["purposeHint"]>,
  counterpartyType: NonNullable<ContextEntry["counterpartyType"]> = "merchant",
  confidence = 78,
): ContextEntry => ({
  id: `${country.code.toLowerCase()}-${id}`,
  aliases,
  signalKind: purposeHint === "travel" ? "travel" : "merchant",
  countryCode: country.code,
  regionCode: country.region,
  currency: country.currency,
  categoryHint,
  purposeHint,
  counterpartyType,
  travelLikely: purposeHint === "travel" || purposeHint === "transport",
  confidence,
});

const countries = {
  VE: { code: "VE", region: "LATAM", currency: "VES" },
  BB: { code: "BB", region: "CAR", currency: "BBD" },
  BS: { code: "BS", region: "CAR", currency: "BSD" },
  BZ: { code: "BZ", region: "CAR", currency: "BZD" },
  GY: { code: "GY", region: "CAR", currency: "GYD" },
  SR: { code: "SR", region: "CAR", currency: "SRD" },
  HT: { code: "HT", region: "CAR", currency: "HTG" },
  AO: { code: "AO", region: "AFR", currency: "AOA" },
  NA: { code: "NA", region: "AFR", currency: "NAD" },
  ZW: { code: "ZW", region: "AFR", currency: "USD" },
  CM: { code: "CM", region: "AFR", currency: "XAF" },
  GA: { code: "GA", region: "AFR", currency: "XAF" },
  CD: { code: "CD", region: "AFR", currency: "CDF" },
  MG: { code: "MG", region: "AFR", currency: "MGA" },
  SC: { code: "SC", region: "AFR", currency: "SCR" },
  CV: { code: "CV", region: "AFR", currency: "CVE" },
  BJ: { code: "BJ", region: "AFR", currency: "XOF" },
  TG: { code: "TG", region: "AFR", currency: "XOF" },
  SL: { code: "SL", region: "AFR", currency: "SLE" },
  LB: { code: "LB", region: "MEA", currency: "LBP" },
  IQ: { code: "IQ", region: "MEA", currency: "IQD" },
  MV: { code: "MV", region: "SAS", currency: "MVR" },
  BT: { code: "BT", region: "SAS", currency: "BTN" },
  PG: { code: "PG", region: "OCE", currency: "PGK" },
  WS: { code: "WS", region: "OCE", currency: "WST" },
  TO: { code: "TO", region: "OCE", currency: "TOP" },
  VU: { code: "VU", region: "OCE", currency: "VUV" },
  SB: { code: "SB", region: "OCE", currency: "SBD" },
  ME: { code: "ME", region: "EUR", currency: "EUR" },
  TJ: { code: "TJ", region: "CAS", currency: "TJS" },
} satisfies Record<string, Country>;

const { VE, BB, BS, BZ, GY, SR, HT, AO, NA, ZW, CM, GA, CD, MG, SC, CV, BJ, TG, SL, LB, IQ, MV, BT, PG, WS, TO, VU, SB, ME, TJ } = countries;

/**
 * Third reviewed worldwide pack. Country qualification is mandatory for
 * shared brands. Payment rails add provenance but never decide whether a row
 * is an expense, peer payment, or movement between the user's own accounts.
 */
export const WORLD_CONTEXT_ENTRIES_3: ContextEntry[] = [
  // Latin America and the Caribbean.
  rail(VE, "pago-movil", ["pago movil venezuela", "pago móvil interbancario venezuela"], "venezuela_pago_movil", 86),
  bank(VE, "bdv", ["banco de venezuela", "bdv venezuela"]),
  merchant(VE, "metro-caracas", ["metro de caracas", "metro caracas venezuela"], "Transport", "transport", "transport_provider"),
  merchant(VE, "central-madeirense", ["central madeirense venezuela", "supermercado central madeirense"], "Groceries", "groceries", "grocer"),
  merchant(VE, "corpoelec", ["corpoelec venezuela", "corporacion electrica nacional venezuela"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(BB, "republic", ["republic bank barbados", "republic bank barbados limited"]),
  bank(BB, "cibc", ["cibc caribbean barbados", "cibc firstcaribbean barbados"]),
  merchant(BB, "transport-board", ["barbados transport board", "transport board barbados bus"], "Transport", "transport", "transport_provider"),
  merchant(BB, "mass-y", ["massystores barbados", "mass y stores barbados"], "Groceries", "groceries", "grocer"),
  merchant(BB, "blp", ["barbados light and power", "blpc barbados electricity"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(BS, "sand-dollar", ["sand dollar bahamas", "bahamian sand dollar wallet"], "bahamas_sand_dollar", 90),
  bank(BS, "bank-bahamas", ["bank of the bahamas", "bank of bahamas limited"]),
  merchant(BS, "jitney", ["nassau jitney bahamas", "bahamas public bus jitney"], "Transport", "transport", "transport_provider"),
  merchant(BS, "super-value", ["super value bahamas", "super value food stores bahamas"], "Groceries", "groceries", "grocer"),
  merchant(BS, "bpl", ["bahamas power and light", "bpl electricity bahamas"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(BZ, "belize-bank", ["belize bank limited", "the belize bank"]),
  bank(BZ, "atlantic", ["atlantic bank belize", "atlantic bank limited belize"]),
  merchant(BZ, "james-bus", ["james bus line belize", "james bus belize"], "Transport", "transport", "transport_provider"),
  merchant(BZ, "brodies", ["brodies supermarket belize", "john brodies belize grocery"], "Groceries", "groceries", "grocer"),
  merchant(BZ, "bel", ["belize electricity limited", "bel electricity belize"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(GY, "mmg", ["mmg mobile money guyana", "mobile money guyana mmg"], "guyana_mmg", 84),
  bank(GY, "republic", ["republic bank guyana", "republic bank guyana limited"]),
  merchant(GY, "minibus", ["georgetown minibus guyana", "guyana public minibus"], "Transport", "transport", "transport_provider"),
  merchant(GY, "mass-y", ["massystores guyana", "mass y stores guyana"], "Groceries", "groceries", "grocer"),
  merchant(GY, "gpl", ["guyana power and light", "gpl electricity guyana"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(SR, "hakrinbank", ["hakrinbank suriname", "hakrin bank suriname"]),
  bank(SR, "dsb", ["de surinaamsche bank", "dsb bank suriname"]),
  merchant(SR, "nvb", ["nationaal vervoer bedrijf suriname", "nvb bus suriname"], "Transport", "transport", "transport_provider"),
  merchant(SR, "chois", ["choi supermarkets suriname", "choi supermarket paramaribo"], "Groceries", "groceries", "grocer"),
  merchant(SR, "ebs", ["energiebedrijven suriname", "ebs electricity suriname"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(HT, "moncash", ["moncash haiti", "digicel moncash haiti"], "haiti_moncash", 86),
  bank(HT, "unibank", ["unibank haiti", "unibank sa haiti"]),
  merchant(HT, "tap-tap", ["tap tap transport haiti", "tap-tap bus haiti"], "Transport", "transport", "transport_provider"),
  merchant(HT, "caribbean", ["caribbean supermarket haiti", "caribbean market port au prince"], "Groceries", "groceries", "grocer"),
  merchant(HT, "edh", ["electricite dhaiti", "edh electricity haiti"], "Bills & Utilities", "utilities", "utility_provider"),

  // Africa.
  rail(AO, "multicaixa", ["multicaixa express angola", "multicaixa angola"], "angola_multicaixa", 88),
  bank(AO, "bfa", ["banco de fomento angola", "bfa angola"]),
  merchant(AO, "tcul", ["tcul luanda", "transportes colectivos urbanos luanda"], "Transport", "transport", "transport_provider"),
  merchant(AO, "kero", ["kero supermercado angola", "kero hypermarket angola"], "Groceries", "groceries", "grocer"),
  merchant(AO, "ende", ["ende angola electricidade", "empresa nacional distribuicao electricidade angola"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(NA, "windhoek", ["bank windhoek namibia", "bank windhoek limited"]),
  bank(NA, "fnb", ["fnb namibia", "first national bank namibia"]),
  merchant(NA, "intercape", ["intercape namibia", "intercape bus namibia"], "Transport", "transport", "transport_provider"),
  merchant(NA, "woermann", ["woermann brock namibia", "woermann supermarket namibia"], "Groceries", "groceries", "grocer"),
  merchant(NA, "nampower", ["nampower namibia", "namibia power corporation"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(ZW, "zipit", ["zipit zimbabwe", "zim switch zipit"], "zimbabwe_zipit", 86),
  bank(ZW, "cbz", ["cbz bank zimbabwe", "commercial bank zimbabwe cbz"]),
  merchant(ZW, "zupco", ["zupco zimbabwe", "zimbabwe united passenger company"], "Transport", "transport", "transport_provider"),
  merchant(ZW, "ok", ["ok zimbabwe supermarket", "ok stores zimbabwe"], "Groceries", "groceries", "grocer"),
  merchant(ZW, "zesa", ["zesa holdings zimbabwe", "zimbabwe electricity transmission distribution"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(CM, "gimacpay", ["gimacpay cameroon", "gimac pay cameroun"], "cemac_gimacpay", 86),
  bank(CM, "afriland", ["afriland first bank cameroon", "afriland cameroun"]),
  merchant(CM, "camrail", ["camrail cameroon", "camrail cameroun train"], "Transport", "transport", "transport_provider"),
  merchant(CM, "carrefour", ["carrefour cameroon", "carrefour cameroun"], "Groceries", "groceries", "grocer"),
  merchant(CM, "eneo", ["eneo cameroon", "eneo cameroun electricity"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(GA, "airtel-money", ["airtel money gabon", "airtel gabon mobile money"], "gabon_mobile_money", 84),
  bank(GA, "bgfi", ["bgfibank gabon", "bgfi bank gabon"]),
  merchant(GA, "transurb", ["trans urb gabon", "transurb libreville"], "Transport", "transport", "transport_provider"),
  merchant(GA, "prix-import", ["prix import gabon", "prix import libreville supermarket"], "Groceries", "groceries", "grocer"),
  merchant(GA, "seeg", ["seeg gabon", "societe energie eau gabon"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(CD, "mpesa", ["m-pesa dr congo", "mpesa rdc"], "drc_mobile_money", 86),
  bank(CD, "rawbank", ["rawbank dr congo", "rawbank rdc"]),
  merchant(CD, "transco", ["transco kinshasa", "transco rdc bus"], "Transport", "transport", "transport_provider"),
  merchant(CD, "kin-marche", ["kin marche rdc", "kin marche kinshasa supermarket"], "Groceries", "groceries", "grocer"),
  merchant(CD, "snel", ["snel rdc electricity", "societe nationale electricite congo"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MG, "mvola", ["mvola madagascar", "telma mvola madagascar"], "madagascar_mvola", 86),
  bank(MG, "bni", ["bni madagascar", "bni banque madagascar"]),
  merchant(MG, "taxi-be", ["taxi be madagascar", "taxi-be antananarivo"], "Transport", "transport", "transport_provider"),
  merchant(MG, "jumbo-score", ["jumbo score madagascar", "score supermarket madagascar"], "Groceries", "groceries", "grocer"),
  merchant(MG, "jirama", ["jirama madagascar", "jiro sy rano malagasy"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(SC, "mcb", ["mcb seychelles", "mauritius commercial bank seychelles"]),
  bank(SC, "scb", ["seychelles commercial bank", "scb seychelles"]),
  merchant(SC, "sptc", ["seychelles public transport corporation", "sptc seychelles"], "Transport", "transport", "transport_provider"),
  merchant(SC, "stc", ["stc hypermarket seychelles", "seychelles trading company hypermarket"], "Groceries", "groceries", "grocer"),
  merchant(SC, "puc", ["public utilities corporation seychelles", "puc seychelles utilities"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(CV, "vinti4", ["vinti4 cabo verde", "rede vinti4 cape verde"], "cabo_verde_vinti4", 84),
  bank(CV, "bca", ["banco comercial atlantico cabo verde", "bca cabo verde"]),
  merchant(CV, "aluguer", ["aluguer transport cabo verde", "hiace aluguer cape verde"], "Transport", "transport", "transport_provider"),
  merchant(CV, "calu-angela", ["calu e angela cabo verde", "calu angela supermarket cape verde"], "Groceries", "groceries", "grocer"),
  merchant(CV, "electra", ["electra cabo verde", "electra electricity cape verde"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(BJ, "mtn-momo", ["mtn mobile money benin", "mtn momo benin"], "benin_mobile_money", 84),
  bank(BJ, "boa", ["bank of africa benin", "boa benin"]),
  merchant(BJ, "baobab-express", ["baobab express benin", "baobab bus benin"], "Transport", "transport", "transport_provider"),
  merchant(BJ, "erevan", ["erevan supermarket benin", "supermarche erevan cotonou"], "Groceries", "groceries", "grocer"),
  merchant(BJ, "sbee", ["sbee benin", "societe beninoise energie electrique"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(TG, "tmoney", ["tmoney togo", "t money togocom"], "togo_tmoney", 86),
  bank(TG, "ecobank", ["ecobank togo", "ecobank transnational togo"]),
  merchant(TG, "sotral", ["sotral togo", "societe transports lome"], "Transport", "transport", "transport_provider"),
  merchant(TG, "ramco", ["ramco supermarket togo", "ramco lome supermarche"], "Groceries", "groceries", "grocer"),
  merchant(TG, "ceet", ["ceet togo", "compagnie energie electrique togo"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(SL, "orange-money", ["orange money sierra leone", "orange mobile money sierra leone"], "sierra_leone_mobile_money", 84),
  bank(SL, "rokel", ["rokel commercial bank", "rokel bank sierra leone"]),
  merchant(SL, "metro", ["metro transport sierra leone", "metro bus freetown"], "Transport", "transport", "transport_provider"),
  merchant(SL, "choithram", ["choithram supermarket sierra leone", "choithrams freetown"], "Groceries", "groceries", "grocer"),
  merchant(SL, "edsa", ["edsa sierra leone", "electricity distribution supply authority sierra leone"], "Bills & Utilities", "utilities", "utility_provider"),

  // Middle East and South Asia.
  rail(LB, "omt-pay", ["omt pay lebanon", "omt wallet lebanon"], "lebanon_omt_pay", 84),
  bank(LB, "audi", ["bank audi lebanon", "بنك عوده لبنان"]),
  merchant(LB, "lcc", ["lebanese commuting company", "lcc bus lebanon"], "Transport", "transport", "transport_provider"),
  merchant(LB, "spinneys", ["spinneys lebanon", "spinneys supermarket lebanon"], "Groceries", "groceries", "grocer"),
  merchant(LB, "edl", ["electricite du liban", "مؤسسة كهرباء لبنان"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(IQ, "zaincash", ["zaincash iraq", "زين كاش العراق"], "iraq_zaincash", 86),
  bank(IQ, "rafidain", ["rafidain bank iraq", "مصرف الرافدين العراق"]),
  merchant(IQ, "iraqi-airways", ["iraqi airways", "الخطوط الجوية العراقية"], "Travel & Lifestyle", "travel", "travel_provider"),
  merchant(IQ, "carrefour", ["carrefour iraq", "كارفور العراق"], "Groceries", "groceries", "grocer"),
  merchant(IQ, "electricity", ["iraq ministry of electricity", "وزارة الكهرباء العراقية"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MV, "favara", ["favara transfer maldives", "favara id maldives"], "maldives_favara", 90),
  bank(MV, "bml", ["bank of maldives", "bml maldives"]),
  merchant(MV, "rtl", ["rtl maldives transport", "raajje transport link"], "Transport", "transport", "transport_provider"),
  merchant(MV, "sto", ["sto supermarket maldives", "state trading organisation maldives supermarket"], "Groceries", "groceries", "grocer"),
  merchant(MV, "stelco", ["stelco maldives", "state electric company maldives"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(BT, "bhutan-qr", ["bhutan qr payment", "rma bhutan qr"], "bhutan_qr", 86),
  bank(BT, "bob", ["bank of bhutan", "bob bhutan bank"]),
  merchant(BT, "city-bus", ["city bus service thimphu", "thimphu city bus bhutan"], "Transport", "transport", "transport_provider"),
  merchant(BT, "fcbl", ["food corporation bhutan", "fcbl bhutan grocery"], "Groceries", "groceries", "grocer"),
  merchant(BT, "bpc", ["bhutan power corporation", "bpc electricity bhutan"], "Bills & Utilities", "utilities", "utility_provider"),

  // Pacific and Central/Eastern Europe.
  bank(PG, "kina", ["kina bank papua new guinea", "kina bank png"]),
  bank(PG, "bsp", ["bsp financial group papua new guinea", "bsp bank png"]),
  merchant(PG, "pmv", ["pmv bus papua new guinea", "public motor vehicle png"], "Transport", "transport", "transport_provider"),
  merchant(PG, "stop-shop", ["stop and shop papua new guinea", "stop n shop png supermarket"], "Groceries", "groceries", "grocer"),
  merchant(PG, "png-power", ["png power limited", "papua new guinea power"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(WS, "bsp", ["bsp bank samoa", "bsp financial group samoa"]),
  bank(WS, "anz", ["anz bank samoa", "anz samoa"]),
  merchant(WS, "shipping", ["samoa shipping corporation", "samoa ferry shipping corporation"], "Transport", "transport", "transport_provider"),
  merchant(WS, "farmer-joe", ["farmer joe supermarket samoa", "farmer joe samoan grocery"], "Groceries", "groceries", "grocer"),
  merchant(WS, "epc", ["electric power corporation samoa", "epc samoa electricity"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(TO, "bsp", ["bsp bank tonga", "bsp financial group tonga"]),
  bank(TO, "anz", ["anz bank tonga", "anz tonga"]),
  merchant(TO, "bus", ["nukualofa bus tonga", "public bus tonga"], "Transport", "transport", "transport_provider"),
  merchant(TO, "molisi", ["molisi supermarket tonga", "molisi tonga grocery"], "Groceries", "groceries", "grocer"),
  merchant(TO, "tonga-power", ["tonga power limited", "tonga electricity power"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(VU, "mvatu", ["m-vatu vanuatu", "vodafone mvatu vanuatu"], "vanuatu_mvatu", 84),
  bank(VU, "bred", ["bred bank vanuatu", "bred vanuatu"]),
  merchant(VU, "bus", ["port vila bus vanuatu", "vanuatu public bus"], "Transport", "transport", "transport_provider"),
  merchant(VU, "abm", ["au bon marche vanuatu", "abm supermarket vanuatu"], "Groceries", "groceries", "grocer"),
  merchant(VU, "unelco", ["unelco vanuatu", "unelco engie vanuatu"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(SB, "bsp", ["bsp bank solomon islands", "bsp financial group solomon islands"]),
  bank(SB, "anz", ["anz bank solomon islands", "anz solomon"]),
  merchant(SB, "bus", ["honiara bus solomon islands", "solomon islands public bus"], "Transport", "transport", "transport_provider"),
  merchant(SB, "bulk-shop", ["bulk shop solomon islands", "bulk shop honiara supermarket"], "Groceries", "groceries", "grocer"),
  merchant(SB, "solomon-power", ["solomon power", "solomon islands electricity authority"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(ME, "ckb", ["crnogorska komercijalna banka", "ckb montenegro"]),
  bank(ME, "nlb", ["nlb banka montenegro", "nlb banka podgorica"]),
  merchant(ME, "podgorica-transit", ["gradski prevoz podgorica", "podgorica public transport"], "Transport", "transport", "transport_provider"),
  merchant(ME, "voli", ["voli supermarket montenegro", "voli crna gora"], "Groceries", "groceries", "grocer"),
  merchant(ME, "epcg", ["elektroprivreda crne gore", "epcg montenegro electricity"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(TJ, "alif", ["alif mobi tajikistan", "алиф моби точикистон"], "tajikistan_alif", 84),
  bank(TJ, "amonatbank", ["amonatbank tajikistan", "амонатбонк точикистон"]),
  merchant(TJ, "dushanbe-bus", ["dushanbe bus tajikistan", "автобус душанбе"] , "Transport", "transport", "transport_provider"),
  merchant(TJ, "paykar", ["paykar supermarket tajikistan", "пайкар супермаркет душанбе"], "Groceries", "groceries", "grocer"),
  merchant(TJ, "barqi", ["barqi tojik", "барки точик electricity"], "Bills & Utilities", "utilities", "utility_provider"),

  // Purpose depth for existing but still shallow country packs.
  merchant({ code: "AL", region: "EUR", currency: "ALL" }, "spitali-amerikan", ["spitali amerikan albania", "american hospital albania"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "AL", region: "EUR", currency: "ALL" }, "one", ["one albania telecom", "one telecommunications albania"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "AL", region: "EUR", currency: "ALL" }, "sophie", ["sophie caffe albania", "sophie coffee tirana"], "Dining", "dining"),
  merchant({ code: "AR", region: "LATAM", currency: "ARS" }, "edesur", ["edesur argentina", "edesur buenos aires"], "Bills & Utilities", "utilities", "utility_provider"),
  merchant({ code: "AR", region: "LATAM", currency: "ARS" }, "hospital-italiano", ["hospital italiano buenos aires", "hospital italiano argentina"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "AR", region: "LATAM", currency: "ARS" }, "personal", ["personal telecom argentina", "personal flow argentina"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "BA", region: "EUR", currency: "BAM" }, "asa-bolnica", ["asa bolnica sarajevo", "asa hospital bosnia"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "BA", region: "EUR", currency: "BAM" }, "bh-telecom", ["bh telecom bosnia", "bh telecom bih"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "BA", region: "EUR", currency: "BAM" }, "zeljo", ["cevabdzinica zeljeznicar sarajevo", "zeljo cevapi bosnia"], "Dining", "dining"),
  merchant({ code: "BD", region: "SAS", currency: "BDT" }, "shwapno", ["shwapno bangladesh", "shwapno supermarket dhaka"], "Groceries", "groceries", "grocer"),
  merchant({ code: "BD", region: "SAS", currency: "BDT" }, "desco", ["desco bangladesh electricity", "dhaka electric supply company"], "Bills & Utilities", "utilities", "utility_provider"),
  merchant({ code: "BD", region: "SAS", currency: "BDT" }, "square-hospital", ["square hospital bangladesh", "square hospitals dhaka"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "BH", region: "MEA", currency: "BHD" }, "al-jazira", ["al jazira supermarket bahrain", "aljazira supermarket bahrain"], "Groceries", "groceries", "grocer"),
  merchant({ code: "BH", region: "MEA", currency: "BHD" }, "royal-bahrain", ["royal bahrain hospital", "rbh hospital bahrain"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "BH", region: "MEA", currency: "BHD" }, "batelco", ["batelco bahrain", "bahrain telecommunications company"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "BN", region: "SEA", currency: "BND" }, "supasave", ["supasave brunei", "supasave supermarket brunei"], "Groceries", "groceries", "grocer"),
  merchant({ code: "BN", region: "SEA", currency: "BND" }, "dart", ["dart brunei transport", "dart ride brunei"], "Transport", "transport", "transport_provider"),
  merchant({ code: "BN", region: "SEA", currency: "BND" }, "jpmc", ["jerudong park medical centre", "jpmc brunei"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "BR", region: "LATAM", currency: "BRL" }, "bilhete-unico", ["bilhete unico sao paulo", "bilhete único são paulo"], "Transport", "transport", "transport_provider"),
  merchant({ code: "BR", region: "LATAM", currency: "BRL" }, "pao-acucar", ["pao de acucar brasil", "pão de açúcar supermercado"], "Groceries", "groceries", "grocer"),
  merchant({ code: "BR", region: "LATAM", currency: "BRL" }, "dasa", ["dasa saude brasil", "dasa diagnosticos brasil"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "BW", region: "AFR", currency: "BWP" }, "gaborone-bus", ["gaborone bus botswana", "botswana bus service gaborone"], "Transport", "transport", "transport_provider"),
  merchant({ code: "BW", region: "AFR", currency: "BWP" }, "bokamoso", ["bokamoso private hospital", "bokamoso hospital botswana"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "BW", region: "AFR", currency: "BWP" }, "btc", ["botswana telecommunications corporation", "btc mobile botswana"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "CZ", region: "EUR", currency: "CZK" }, "motol", ["fn motol prague", "university hospital motol"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "CZ", region: "EUR", currency: "CZK" }, "o2", ["o2 czech republic telecom", "o2 cz vyuctovani"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "CZ", region: "EUR", currency: "CZK" }, "lokal", ["lokal restaurant prague", "lokál praha restaurant"], "Dining", "dining"),
  merchant({ code: "ET", region: "AFR", currency: "ETB" }, "shoa", ["shoa supermarket ethiopia", "shoa shopping ethiopia"], "Groceries", "groceries", "grocer"),
  merchant({ code: "ET", region: "AFR", currency: "ETB" }, "tikur-anbessa", ["tikur anbessa hospital", "black lion hospital ethiopia"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "ET", region: "AFR", currency: "ETB" }, "ethio-telecom", ["ethio telecom", "ethiotelecom ethiopia"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "GE", region: "EUR", currency: "GEL" }, "evex", ["evex hospitals georgia", "evex medical georgia"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "GE", region: "EUR", currency: "GEL" }, "magticom", ["magticom georgia", "magti telecom georgia"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "GE", region: "EUR", currency: "GEL" }, "machakhela", ["machakhela restaurant georgia", "machakhela tbilisi"], "Dining", "dining"),
  merchant({ code: "GH", region: "AFR", currency: "GHS" }, "metro-mass", ["metro mass transit ghana", "metro mass bus ghana"], "Transport", "transport", "transport_provider"),
  merchant({ code: "GH", region: "AFR", currency: "GHS" }, "melcom", ["melcom ghana supermarket", "melcom stores ghana"], "Groceries", "groceries", "grocer"),
  merchant({ code: "GH", region: "AFR", currency: "GHS" }, "nyaho", ["nyaho medical centre ghana", "nyaho clinic accra"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "IL", region: "MEA", currency: "ILS" }, "iec", ["israel electric corporation", "חברת החשמל לישראל"], "Bills & Utilities", "utilities", "utility_provider"),
  merchant({ code: "IL", region: "MEA", currency: "ILS" }, "clalit", ["clalit health services", "שירותי בריאות כללית"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "IL", region: "MEA", currency: "ILS" }, "aroma", ["aroma espresso bar israel", "ארומה ישראל"], "Dining", "dining"),
  merchant({ code: "JO", region: "MEA", currency: "JOD" }, "jepco", ["jepco jordan", "jordan electric power company"], "Bills & Utilities", "utilities", "utility_provider"),
  merchant({ code: "JO", region: "MEA", currency: "JOD" }, "specialty-hospital", ["specialty hospital jordan", "المستشفى التخصصي الاردن"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "JO", region: "MEA", currency: "JOD" }, "orange", ["orange jordan telecom", "اورنج الاردن"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "MA", region: "MEA", currency: "MAD" }, "akdital", ["akdital hospital morocco", "akdital maroc"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "MA", region: "MEA", currency: "MAD" }, "maroc-telecom", ["maroc telecom", "اتصالات المغرب"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "MA", region: "MEA", currency: "MAD" }, "la-sqala", ["la sqala casablanca", "restaurant la sqala maroc"], "Dining", "dining"),
  merchant({ code: "MM", region: "SEA", currency: "MMK" }, "city-mart", ["city mart myanmar", "city mart supermarket yangon"], "Groceries", "groceries", "grocer"),
  merchant({ code: "MM", region: "SEA", currency: "MMK" }, "ybs", ["yangon bus service", "ybs bus myanmar"], "Transport", "transport", "transport_provider"),
  merchant({ code: "MM", region: "SEA", currency: "MMK" }, "pun-hlaing", ["pun hlaing hospitals", "pun hlaing hospital myanmar"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "NG", region: "AFR", currency: "NGN" }, "lagbus", ["lagbus lagos", "lagos bus services nigeria"], "Transport", "transport", "transport_provider"),
  merchant({ code: "NG", region: "AFR", currency: "NGN" }, "shoprite", ["shoprite nigeria", "shoprite supermarket nigeria"], "Groceries", "groceries", "grocer"),
  merchant({ code: "NG", region: "AFR", currency: "NGN" }, "reddington", ["reddington hospital nigeria", "reddington hospital lagos"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "NP", region: "SAS", currency: "NPR" }, "bhatbhateni", ["bhat bhateni supermarket nepal", "bhatbhateni nepal"], "Groceries", "groceries", "grocer"),
  merchant({ code: "NP", region: "SAS", currency: "NPR" }, "sajha", ["sajha yatayat nepal", "sajha bus kathmandu"], "Transport", "transport", "transport_provider"),
  merchant({ code: "NP", region: "SAS", currency: "NPR" }, "norvic", ["norvic hospital nepal", "norvic international hospital"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "NZ", region: "OCE", currency: "NZD" }, "southern-cross", ["southern cross healthcare new zealand", "southern cross nz health"], "Health & Wellness", "healthcare", "healthcare_provider"),
  merchant({ code: "NZ", region: "OCE", currency: "NZD" }, "spark", ["spark new zealand telecom", "spark nz mobile"], "Bills & Utilities", "telecom", "telecom_provider"),
  merchant({ code: "NZ", region: "OCE", currency: "NZD" }, "coffee-club", ["the coffee club new zealand", "coffee club nz"], "Dining", "dining"),
  merchant({ code: "PK", region: "SAS", currency: "PKR" }, "imtiaz", ["imtiaz supermarket pakistan", "imtiaz store pakistan"], "Groceries", "groceries", "grocer"),
  merchant({ code: "PK", region: "SAS", currency: "PKR" }, "k-electric", ["k electric pakistan", "k-electric karachi"], "Bills & Utilities", "utilities", "utility_provider"),
  merchant({ code: "PK", region: "SAS", currency: "PKR" }, "aga-khan", ["aga khan university hospital pakistan", "aku hospital pakistan"], "Health & Wellness", "healthcare", "healthcare_provider"),
];

const profile = (
  countryCode: string,
  regionCode: string,
  locales: string[],
  languages: string[],
  dateOrder: RegionalParsingProfile["dateOrder"],
  decimalSeparator: RegionalParsingProfile["decimalSeparator"],
  groupingSeparator: RegionalParsingProfile["groupingSeparator"],
  defaultCurrency: string,
  legalEntitySuffixes: string[],
  confidence = 68,
): RegionalParsingProfile => ({
  countryCode, regionCode, locales, primaryLocale: locales[0], languages, dateOrder,
  decimalSeparator, groupingSeparator, defaultCurrency, legalEntitySuffixes, confidence,
});

export const WORLD_REGIONAL_PROFILES_3: RegionalParsingProfile[] = [
  profile("VE", "LATAM", ["es-VE", "en-VE"], ["es", "en"], "dmy", ",", ".", "VES", ["ca", "sa", "srl"], 70),
  profile("BB", "CAR", ["en-BB"], ["en"], "dmy", ".", ",", "BBD", ["ltd", "limited", "inc"]),
  profile("BS", "CAR", ["en-BS"], ["en"], "dmy", ".", ",", "BSD", ["ltd", "limited", "inc"], 72),
  profile("BZ", "CAR", ["en-BZ", "es-BZ"], ["en", "es"], "dmy", ".", ",", "BZD", ["ltd", "limited", "inc"]),
  profile("GY", "CAR", ["en-GY"], ["en"], "dmy", ".", ",", "GYD", ["ltd", "limited", "inc"]),
  profile("SR", "CAR", ["nl-SR", "en-SR"], ["nl", "en"], "dmy", ",", ".", "SRD", ["nv", "bv", "stichting"]),
  profile("HT", "CAR", ["fr-HT", "ht-HT"], ["fr", "ht"], "dmy", ",", " ", "HTG", ["sa", "sarl", "societe"]),
  profile("AO", "AFR", ["pt-AO", "en-AO"], ["pt", "en"], "dmy", ",", ".", "AOA", ["lda", "sa", "limitada"], 70),
  profile("NA", "AFR", ["en-NA", "af-NA"], ["en", "af"], "dmy", ".", ",", "NAD", ["pty ltd", "cc", "limited"]),
  profile("ZW", "AFR", ["en-ZW", "sn-ZW"], ["en", "sn"], "dmy", ".", ",", "USD", ["pvt ltd", "limited", "plc"], 70),
  profile("CM", "AFR", ["fr-CM", "en-CM"], ["fr", "en"], "dmy", ",", " ", "XAF", ["sarl", "sa", "ets"]),
  profile("GA", "AFR", ["fr-GA", "en-GA"], ["fr", "en"], "dmy", ",", " ", "XAF", ["sarl", "sa", "ets"]),
  profile("CD", "AFR", ["fr-CD", "sw-CD"], ["fr", "sw"], "dmy", ",", " ", "CDF", ["sarl", "sa", "sprl"]),
  profile("MG", "AFR", ["mg-MG", "fr-MG"], ["mg", "fr"], "dmy", ",", " ", "MGA", ["sarl", "sa", "eurl"]),
  profile("SC", "AFR", ["en-SC", "fr-SC"], ["en", "fr"], "dmy", ".", ",", "SCR", ["ltd", "limited", "pty"]),
  profile("CV", "AFR", ["pt-CV", "kea-CV"], ["pt", "kea"], "dmy", ",", ".", "CVE", ["lda", "sa", "unipessoal"]),
  profile("BJ", "AFR", ["fr-BJ", "en-BJ"], ["fr", "en"], "dmy", ",", " ", "XOF", ["sarl", "sa", "ets"]),
  profile("TG", "AFR", ["fr-TG", "en-TG"], ["fr", "en"], "dmy", ",", " ", "XOF", ["sarl", "sa", "ets"]),
  profile("SL", "AFR", ["en-SL"], ["en"], "dmy", ".", ",", "SLE", ["ltd", "limited", "plc"]),
  profile("LB", "MEA", ["ar-LB", "en-LB", "fr-LB"], ["ar", "en", "fr"], "dmy", ".", ",", "LBP", ["sal", "sarl", "offshore"], 70),
  profile("IQ", "MEA", ["ar-IQ", "en-IQ", "ku-IQ"], ["ar", "en", "ku"], "dmy", ".", ",", "IQD", ["ltd", "llc", "co"], 70),
  profile("MV", "SAS", ["dv-MV", "en-MV"], ["dv", "en"], "dmy", ".", ",", "MVR", ["pvt ltd", "plc", "limited"], 74),
  profile("BT", "SAS", ["dz-BT", "en-BT"], ["dz", "en"], "ymd", ".", ",", "BTN", ["pvt ltd", "limited", "ltd"], 70),
  profile("PG", "OCE", ["en-PG", "tpi-PG"], ["en", "tpi"], "dmy", ".", ",", "PGK", ["ltd", "limited", "inc"]),
  profile("WS", "OCE", ["en-WS", "sm-WS"], ["en", "sm"], "dmy", ".", ",", "WST", ["ltd", "limited", "inc"]),
  profile("TO", "OCE", ["en-TO", "to-TO"], ["en", "to"], "dmy", ".", ",", "TOP", ["ltd", "limited", "inc"]),
  profile("VU", "OCE", ["fr-VU", "en-VU", "bi-VU"], ["fr", "en", "bi"], "dmy", ".", ",", "VUV", ["ltd", "limited", "sa"]),
  profile("SB", "OCE", ["en-SB"], ["en"], "dmy", ".", ",", "SBD", ["ltd", "limited", "inc"]),
  profile("ME", "EUR", ["sr-ME", "en-ME"], ["sr", "en"], "dmy", ",", ".", "EUR", ["doo", "ad", "preduzetnik"], 70),
  profile("TJ", "CAS", ["tg-TJ", "ru-TJ"], ["tg", "ru"], "dmy", ",", " ", "TJS", ["jsc", "llc", "individual entrepreneur"], 68),
];
