import type { ContextEntry } from "@/lib/context-corpus";

type Seed = [id: string, aliases: [string, string]];
type Pack = [country: string, region: string, currency: string, tax: Seed, social: Seed];

const entry = (pack: Pack, seed: Seed, purposeHint: "tax" | "government_contribution"): ContextEntry => ({
  id: `${pack[0].toLowerCase()}-fiscal-3-${seed[0]}`,
  aliases: seed[1],
  signalKind: "merchant",
  countryCode: pack[0],
  regionCode: pack[1],
  currency: pack[2],
  purposeHint,
  counterpartyType: "government",
  confidence: 82,
});

/** Country-qualified tax and social-protection context for the remaining represented markets. */
const PACKS: Pack[] = [
  ["MO", "EAS", "MOP", ["dsf", ["Financial Services Bureau Macau tax", "DSF Macao tax payment"]], ["fss", ["Social Security Fund Macau contribution", "FSS Macao payment"]]],
  ["GU", "OCE", "USD", ["drt", ["Department Revenue Taxation Guam", "Guam DRT tax payment"]], ["grf", ["Government Retirement Fund Guam contribution", "Guam Retirement Fund payment"]]],
  ["MW", "AFR", "MWK", ["mra", ["Malawi Revenue Authority tax", "MRA Malawi tax payment"]], ["nps", ["National Pension Scheme Malawi contribution", "Malawi pension contribution payment"]]],
  ["BZ", "CAR", "BZD", ["bts", ["Belize Tax Service payment", "Belize Tax Service Department"]], ["ssb", ["Social Security Board Belize contribution", "Belize SSB payment"]]],
  ["GY", "CAR", "GYD", ["gra", ["Guyana Revenue Authority tax", "GRA Guyana tax payment"]], ["nis", ["National Insurance Scheme Guyana contribution", "NIS Guyana payment"]]],
  ["SR", "CAR", "SRD", ["belastingdienst", ["Belastingdienst Suriname tax", "Suriname Tax Administration payment"]], ["apf", ["Algemeen Pensioenfonds Suriname contribution", "Suriname pension fund payment"]]],
  ["HT", "CAR", "HTG", ["dgi", ["Direction Generale Impots Haiti", "DGI Haiti tax payment"]], ["ona", ["Office National Assurance Vieillesse Haiti", "ONA Haiti contribution"]]],
  ["AO", "AFR", "AOA", ["agt", ["Administracao Geral Tributaria Angola", "AGT Angola tax payment"]], ["inss", ["INSS Angola contribution", "Instituto Nacional Seguranca Social Angola"]]],
  ["NA", "AFR", "NAD", ["namra", ["Namibia Revenue Agency tax", "NamRA Namibia tax payment"]], ["ssc", ["Social Security Commission Namibia contribution", "SSC Namibia payment"]]],
  ["CM", "AFR", "XAF", ["dgi", ["Direction Generale Impots Cameroon", "DGI Cameroon tax payment"]], ["cnps", ["CNPS Cameroon contribution", "Caisse Nationale Prevoyance Sociale Cameroon"]]],
  ["GA", "AFR", "XAF", ["dgi", ["Direction Generale Impots Gabon", "DGI Gabon tax payment"]], ["cnss", ["CNSS Gabon contribution", "Caisse Nationale Securite Sociale Gabon"]]],
  ["CD", "AFR", "CDF", ["dgi", ["Direction Generale Impots DR Congo", "DGI Congo Kinshasa tax payment"]], ["cnss", ["CNSS DR Congo contribution", "Caisse Nationale Securite Sociale Congo Kinshasa"]]],
  ["MG", "AFR", "MGA", ["dgi", ["Direction Generale Impots Madagascar", "DGI Madagascar tax payment"]], ["cnaps", ["CNaPS Madagascar contribution", "Caisse Nationale Prevoyance Sociale Madagascar"]]],
  ["SC", "AFR", "SCR", ["src", ["Seychelles Revenue Commission tax", "SRC Seychelles tax payment"]], ["sps", ["Seychelles Pension Scheme contribution", "SPS Seychelles payment"]]],
  ["CV", "AFR", "CVE", ["dnre", ["Direcao Nacional Receitas Estado Cabo Verde", "DNRE Cabo Verde tax payment"]], ["inps", ["INPS Cabo Verde contribution", "Instituto Nacional Previdencia Social Cabo Verde"]]],
  ["BJ", "AFR", "XOF", ["dgi", ["Direction Generale Impots Benin", "DGI Benin tax payment"]], ["cnss", ["CNSS Benin contribution", "Caisse Nationale Securite Sociale Benin"]]],
  ["TG", "AFR", "XOF", ["otr", ["Office Togolais Recettes tax payment", "OTR Togo tax"]], ["cnss", ["CNSS Togo contribution", "Caisse Nationale Securite Sociale Togo"]]],
  ["SL", "AFR", "SLE", ["nra", ["National Revenue Authority Sierra Leone", "NRA Sierra Leone tax payment"]], ["nassit", ["NASSIT Sierra Leone contribution", "National Social Security Insurance Trust Sierra Leone"]]],
  ["LB", "MEA", "LBP", ["revenue", ["Revenue Directorate Lebanon tax", "Ministry Finance Lebanon tax payment"]], ["nssf", ["National Social Security Fund Lebanon contribution", "NSSF Lebanon payment"]]],
  ["IQ", "MEA", "IQD", ["gct", ["General Commission Taxes Iraq", "GCT Iraq tax payment"]], ["pssf", ["Pension Social Security Fund Iraq", "Iraq pension contribution payment"]]],
  ["MV", "SAS", "MVR", ["mira", ["Maldives Inland Revenue Authority", "MIRA Maldives tax payment"]], ["mpao", ["Maldives Pension Administration Office", "MPAO Maldives contribution"]]],
  ["BT", "SAS", "BTN", ["drc", ["Department Revenue Customs Bhutan", "DRC Bhutan tax payment"]], ["nppf", ["National Pension Provident Fund Bhutan", "NPPF Bhutan contribution"]]],
  ["WS", "OCE", "WST", ["mcr", ["Ministry Customs Revenue Samoa", "Samoa tax administration payment"]], ["npf", ["Samoa National Provident Fund contribution", "SNPF Samoa payment"]]],
  ["TO", "OCE", "TOP", ["mrc", ["Ministry Revenue Customs Tonga", "Tonga tax administration payment"]], ["trfb", ["Tonga Retirement Fund Board contribution", "TRFB Tonga payment"]]],
  ["VU", "OCE", "VUV", ["cir", ["Customs Inland Revenue Vanuatu", "Vanuatu tax administration payment"]], ["vnpf", ["Vanuatu National Provident Fund contribution", "VNPF Vanuatu payment"]]],
  ["SB", "OCE", "SBD", ["ird", ["Inland Revenue Division Solomon Islands", "Solomon Islands tax payment IRD"]], ["sinpf", ["Solomon Islands National Provident Fund", "SINPF contribution payment"]]],
  ["ME", "EUR", "EUR", ["rca", ["Revenue Customs Administration Montenegro", "Montenegro tax administration payment"]], ["pio", ["Pension Disability Insurance Fund Montenegro", "PIO Montenegro contribution"]]],
  ["TJ", "CAS", "TJS", ["tax-committee", ["Tax Committee Tajikistan payment", "Tajikistan tax administration"]], ["asip", ["Agency Social Insurance Pensions Tajikistan", "Tajikistan social insurance contribution"]]],
  ["AD", "EUR", "EUR", ["dtf", ["Department Tributs Fronteres Andorra", "Andorra tax administration payment"]], ["cass", ["CASS Andorra contribution", "Caixa Andorrana Seguretat Social payment"]]],
  ["LI", "EUR", "CHF", ["fiscal-authority", ["Fiscal Authority Liechtenstein tax", "Liechtenstein tax administration payment"]], ["ahv", ["AHV IV FAK Liechtenstein contribution", "Liechtenstein social insurance payment"]]],
  ["MC", "EUR", "EUR", ["dsf", ["Department Tax Services Monaco", "Monaco tax administration payment"]], ["caisses-sociales", ["Caisses Sociales Monaco contribution", "Monaco social funds payment"]]],
  ["SM", "EUR", "EUR", ["tax-office", ["Tax Office San Marino payment", "Ufficio Tributario San Marino"]], ["iss", ["Social Security Institute San Marino", "ISS San Marino contribution"]]],
  ["XK", "EUR", "EUR", ["tak", ["Tax Administration Kosovo payment", "TAK Kosovo tax"]], ["kpst", ["Kosovo Pension Savings Trust contribution", "KPST Kosovo payment"]]],
  ["BY", "EUR", "BYN", ["mtd", ["Ministry Taxes Duties Belarus", "Belarus tax administration payment"]], ["fsp", ["Social Protection Fund Belarus contribution", "Belarus FSP payment"]]],
  ["IR", "MEA", "IRR", ["inta", ["Iranian National Tax Administration", "INTA Iran tax payment"]], ["sso", ["Social Security Organization Iran contribution", "Iran SSO payment"]]],
  ["PS", "MEA", "ILS", ["mof", ["Ministry Finance Palestine tax", "Palestinian tax administration payment"]], ["ppa", ["Palestinian Pension Agency contribution", "PPA Palestine payment"]]],
  ["YE", "MEA", "YER", ["tax-authority", ["Tax Authority Yemen payment", "Yemen tax administration"]], ["gasip", ["General Authority Social Insurance Pensions Yemen", "Yemen social insurance contribution"]]],
  ["LY", "MEA", "LYD", ["tax-authority", ["Tax Authority Libya payment", "Libyan tax administration"]], ["ssf", ["Social Security Fund Libya contribution", "Libya SSF payment"]]],
  ["ML", "AFR", "XOF", ["dgi", ["Direction Generale Impots Mali", "DGI Mali tax payment"]], ["inps", ["INPS Mali contribution", "Institut National Prevoyance Sociale Mali"]]],
  ["BF", "AFR", "XOF", ["dgi", ["Direction Generale Impots Burkina Faso", "DGI Burkina tax payment"]], ["cnss", ["CNSS Burkina Faso contribution", "Caisse Nationale Securite Sociale Burkina"]]],
  ["NE", "AFR", "XOF", ["dgi", ["Direction Generale Impots Niger", "DGI Niger tax payment"]], ["cnss", ["CNSS Niger contribution", "Caisse Nationale Securite Sociale Niger"]]],
  ["GN", "AFR", "GNF", ["dni", ["Direction Nationale Impots Guinea", "DNI Guinea tax payment"]], ["cnss", ["CNSS Guinea contribution", "Caisse Nationale Securite Sociale Guinea"]]],
  ["LR", "AFR", "LRD", ["lra", ["Liberia Revenue Authority tax", "LRA Liberia tax payment"]], ["nasscorp", ["NASSCORP Liberia contribution", "National Social Security Liberia payment"]]],
  ["GM", "AFR", "GMD", ["gra", ["Gambia Revenue Authority tax", "GRA Gambia tax payment"]], ["sshfc", ["SSHFC Gambia contribution", "Social Security Housing Finance Gambia"]]],
  ["MR", "AFR", "MRU", ["dgi", ["Direction Generale Impots Mauritania", "DGI Mauritania tax payment"]], ["cnss", ["CNSS Mauritania contribution", "Caisse Nationale Securite Sociale Mauritania"]]],
  ["SD", "AFR", "SDG", ["tax-chamber", ["Taxation Chamber Sudan payment", "Sudan tax administration"]], ["nsif", ["National Social Insurance Fund Sudan", "NSIF Sudan contribution"]]],
  ["DJ", "AFR", "DJF", ["dgi", ["Direction Generale Impots Djibouti", "DGI Djibouti tax payment"]], ["cnss", ["CNSS Djibouti contribution", "Caisse Nationale Securite Sociale Djibouti"]]],
  ["SO", "AFR", "SOS", ["ird", ["Inland Revenue Department Somalia", "Ministry Finance Somalia tax payment"]], ["social-protection", ["Social Protection Department Somalia payment", "Somalia social protection contribution"]]],
  ["LS", "AFR", "LSL", ["rsl", ["Revenue Services Lesotho tax", "RSL Lesotho tax payment"]], ["pension-fund", ["Lesotho Pension Fund contribution", "Public Officers Pension Lesotho payment"]]],
  ["SZ", "AFR", "SZL", ["ers", ["Eswatini Revenue Service tax", "ERS Eswatini tax payment"]], ["enpf", ["Eswatini National Provident Fund", "ENPF Eswatini contribution"]]],
  ["CG", "AFR", "XAF", ["dgi", ["Direction Generale Impots Congo Brazzaville", "DGI Republic Congo tax payment"]], ["cnss", ["CNSS Congo Brazzaville contribution", "Caisse Nationale Securite Sociale Republic Congo"]]],
  ["CF", "AFR", "XAF", ["dgi", ["Direction Generale Impots Central African Republic", "DGI Central African Republic tax"]], ["cnss", ["CNSS Central African Republic contribution", "Caisse Nationale Securite Sociale Bangui"]]],
  ["GQ", "AFR", "XAF", ["dgi", ["Direccion General Impuestos Equatorial Guinea", "DGI Equatorial Guinea tax payment"]], ["inseso", ["INSESO Equatorial Guinea contribution", "Social Security Institute Equatorial Guinea"]]],
  ["ST", "AFR", "STN", ["tax-directorate", ["Directorate Taxes Sao Tome Principe", "Sao Tome tax administration payment"]], ["inss", ["INSS Sao Tome Principe contribution", "Social Security Sao Tome payment"]]],
  ["KM", "AFR", "KMF", ["agi", ["General Administration Taxes Comoros", "Comoros tax administration payment"]], ["cpr", ["Caisse Retraites Comoros contribution", "Comoros pension fund payment"]]],
  ["TM", "CAS", "TMT", ["sts", ["State Tax Service Turkmenistan", "Turkmenistan tax administration payment"]], ["pension-fund", ["Pension Fund Turkmenistan contribution", "Turkmenistan social insurance payment"]]],
  ["AF", "SAS", "AFN", ["ard", ["Afghanistan Revenue Department tax", "ARD Afghanistan tax payment"]], ["pension-treasury", ["Pension Treasury Afghanistan contribution", "Afghanistan government pension payment"]]],
  ["PW", "OCE", "USD", ["brt", ["Bureau Revenue Taxation Palau", "Palau tax administration payment"]], ["cspp", ["Civil Service Pension Plan Palau", "Palau pension contribution"]]],
  ["AG", "CAR", "XCD", ["ird", ["Inland Revenue Department Antigua Barbuda", "Antigua Barbuda tax payment"]], ["ssb", ["Social Security Board Antigua Barbuda", "Antigua Barbuda contribution"]]],
  ["BI", "AFR", "BIF", ["obr", ["Office Burundais Recettes tax", "OBR Burundi tax payment"]], ["inss", ["INSS Burundi contribution", "Institut National Securite Sociale Burundi"]]],
  ["TD", "AFR", "XAF", ["dgi", ["Direction Generale Impots Chad", "DGI Chad tax payment"]], ["cnps", ["CNPS Chad contribution", "Caisse Nationale Prevoyance Sociale Chad"]]],
  ["CU", "CAR", "CUP", ["onat", ["National Tax Administration Office Cuba", "ONAT Cuba tax payment"]], ["inass", ["INASS Cuba social security", "National Social Security Institute Cuba"]]],
  ["DM", "CAR", "XCD", ["ird", ["Inland Revenue Division Dominica", "Dominica tax administration payment"]], ["dss", ["Dominica Social Security contribution", "DSS Dominica payment"]]],
  ["ER", "AFR", "ERN", ["ird", ["Inland Revenue Department Eritrea", "Eritrea tax administration payment"]], ["pension-scheme", ["Pension Scheme Eritrea contribution", "Eritrea social insurance payment"]]],
  ["GD", "CAR", "XCD", ["ird", ["Inland Revenue Division Grenada", "Grenada tax administration payment"]], ["nis", ["National Insurance Scheme Grenada", "NIS Grenada contribution"]]],
  ["GW", "AFR", "XOF", ["dgci", ["Directorate Contributions Taxes Guinea Bissau", "Guinea Bissau tax administration payment"]], ["inss", ["INSS Guinea Bissau contribution", "Social Security Guinea Bissau payment"]]],
  ["MH", "OCE", "USD", ["dcrt", ["Division Customs Revenue Taxation Marshall Islands", "Marshall Islands tax administration"]], ["rmissa", ["Marshall Islands Social Security Administration", "MISSA Marshall Islands contribution"]]],
  ["FM", "OCE", "USD", ["dfa", ["Department Finance Administration Tax Micronesia", "FSM tax administration payment"]], ["fsmssa", ["FSM Social Security Administration contribution", "Micronesia social security payment"]]],
  ["KN", "CAR", "XCD", ["ird", ["Inland Revenue Department Saint Kitts Nevis", "St Kitts Nevis tax payment"]], ["ssb", ["Social Security Board Saint Kitts Nevis", "St Kitts Nevis contribution"]]],
  ["LC", "CAR", "XCD", ["ird", ["Inland Revenue Department Saint Lucia", "Saint Lucia tax payment"]], ["nic", ["National Insurance Corporation Saint Lucia", "NIC Saint Lucia contribution"]]],
  ["VC", "CAR", "XCD", ["ird", ["Inland Revenue Department Saint Vincent Grenadines", "SVG tax payment"]], ["nis", ["National Insurance Services Saint Vincent", "NIS SVG contribution"]]],
  ["SS", "AFR", "SSP", ["nra", ["National Revenue Authority South Sudan", "NRA South Sudan tax payment"]], ["nsif", ["National Social Insurance Fund South Sudan", "NSIF South Sudan contribution"]]],
  ["SY", "MEA", "SYP", ["gctf", ["General Commission Taxes Fees Syria", "Syria tax administration payment"]], ["gosi", ["General Organization Social Insurance Syria", "GOSI Syria contribution"]]],
  ["TL", "SEA", "USD", ["tax-authority", ["Tax Authority Timor Leste payment", "Autoridade Tributaria Timor Leste"]], ["inss", ["INSS Timor Leste contribution", "Social Security Timor Leste payment"]]],
  ["TV", "OCE", "AUD", ["cto", ["Customs Taxation Office Tuvalu", "Tuvalu tax administration payment"]], ["tnpf", ["Tuvalu National Provident Fund contribution", "TNPF Tuvalu payment"]]],
  ["RU", "EUR", "RUB", ["fts", ["Federal Tax Service Russia payment", "FTS Russian tax"]], ["sfr", ["Social Fund Russia contribution", "SFR Russian social insurance"]]],
];

export const WORLD_FISCAL_CONTEXT_ENTRIES_3: ContextEntry[] = PACKS.flatMap((pack) => [
  entry(pack, pack[3], "tax"),
  entry(pack, pack[4], "government_contribution"),
]);
