import type { ContextEntry } from "@/lib/context-corpus";

type Seed = [id: string, aliases: [string, string]];
type Pack = [country: string, region: string, currency: string, tax: Seed, social: Seed];

const entry = (pack: Pack, seed: Seed, purposeHint: "tax" | "government_contribution"): ContextEntry => ({
  id: `${pack[0].toLowerCase()}-fiscal-2-${seed[0]}`,
  aliases: seed[1],
  signalKind: "merchant",
  countryCode: pack[0],
  regionCode: pack[1],
  currency: pack[2],
  purposeHint,
  counterpartyType: "government",
  confidence: 84,
});

/** Tax and statutory social-protection counterparties for 60 additional markets. */
const PACKS: Pack[] = [
  ["PH", "SEA", "PHP", ["bir", ["Bureau Internal Revenue Philippines tax", "BIR Philippines tax payment"]], ["sss", ["Social Security System Philippines contribution", "SSS Philippines contribution payment"]]],
  ["SG", "SEA", "SGD", ["iras", ["Inland Revenue Authority Singapore tax", "IRAS Singapore tax payment"]], ["cpf", ["Central Provident Fund Singapore contribution", "CPF Board Singapore payment"]]],
  ["MY", "SEA", "MYR", ["irbm", ["Inland Revenue Board Malaysia tax", "LHDN Malaysia tax payment"]], ["epf", ["Employees Provident Fund Malaysia contribution", "KWSP Malaysia contribution"]]],
  ["ID", "SEA", "IDR", ["djp", ["Directorate General Taxes Indonesia", "DJP Indonesia tax payment"]], ["bpjs-tk", ["BPJS Ketenagakerjaan Indonesia contribution", "BPJSTK Indonesia payment"]]],
  ["TH", "SEA", "THB", ["rd", ["Revenue Department Thailand tax", "Thai Revenue Department payment"]], ["sso", ["Social Security Office Thailand contribution", "SSO Thailand payment"]]],
  ["VN", "SEA", "VND", ["gdt", ["General Department Taxation Vietnam", "GDT Vietnam tax payment"]], ["vss", ["Vietnam Social Security contribution", "VSS Vietnam contribution payment"]]],
  ["KH", "SEA", "KHR", ["gdt", ["General Department Taxation Cambodia", "GDT Cambodia tax payment"]], ["nssf", ["National Social Security Fund Cambodia", "NSSF Cambodia contribution"]]],
  ["MM", "SEA", "MMK", ["ird", ["Internal Revenue Department Myanmar", "IRD Myanmar tax payment"]], ["ssb", ["Social Security Board Myanmar contribution", "SSB Myanmar payment"]]],
  ["BN", "SEA", "BND", ["revenue-division", ["Revenue Division Brunei tax", "MOFE Brunei tax payment"]], ["tap", ["Tabung Amanah Pekerja Brunei contribution", "TAP Brunei payment"]]],
  ["LA", "SEA", "LAK", ["tax-department", ["Tax Department Lao PDR payment", "Ministry Finance Laos tax"]], ["nssf", ["National Social Security Fund Laos", "NSSF Lao PDR contribution"]]],
  ["HK", "EAS", "HKD", ["ird", ["Inland Revenue Department Hong Kong tax", "IRD Hong Kong tax payment"]], ["mpfa", ["Mandatory Provident Fund Hong Kong contribution", "MPFA Hong Kong payment"]]],
  ["TW", "EAS", "TWD", ["ntb", ["National Taxation Bureau Taiwan payment", "Taiwan National Tax Bureau tax"]], ["bli", ["Bureau Labor Insurance Taiwan contribution", "BLI Taiwan social insurance"]]],
  ["AE", "MEA", "AED", ["fta", ["Federal Tax Authority UAE payment", "FTA United Arab Emirates tax"]], ["gpssa", ["GPSSA UAE pension contribution", "General Pension Social Security UAE"]]],
  ["US", "NAM", "USD", ["irs", ["Internal Revenue Service United States tax", "IRS US tax payment"]], ["ssa", ["Social Security Administration US contribution", "SSA United States social security"]]],
  ["GB", "EUR", "GBP", ["hmrc", ["HM Revenue Customs United Kingdom tax", "HMRC UK tax payment"]], ["national-insurance", ["HMRC National Insurance contribution UK", "United Kingdom National Insurance payment"]]],
  ["AU", "OCE", "AUD", ["ato", ["Australian Taxation Office payment", "ATO Australia tax"]], ["services-australia", ["Services Australia social security payment", "Centrelink Australia government contribution"]]],
  ["CA", "NAM", "CAD", ["cra", ["Canada Revenue Agency tax payment", "CRA Canada tax"]], ["cpp", ["Canada Pension Plan contribution", "CRA CPP contribution payment"]]],
  ["SA", "MEA", "SAR", ["zatca", ["ZATCA Saudi Arabia tax payment", "Zakat Tax Customs Authority Saudi"]], ["gosi", ["GOSI Saudi Arabia contribution", "General Organization Social Insurance Saudi"]]],
  ["QA", "MEA", "QAR", ["gta", ["General Tax Authority Qatar payment", "GTA Qatar tax"]], ["grsia", ["General Retirement Social Insurance Qatar", "GRSIA Qatar contribution"]]],
  ["KW", "MEA", "KWD", ["tax-administration", ["Kuwait Tax Administration payment", "Ministry Finance Kuwait tax"]], ["pifss", ["PIFSS Kuwait contribution", "Public Institution Social Security Kuwait"]]],
  ["NZ", "OCE", "NZD", ["ird", ["Inland Revenue New Zealand tax", "IRD New Zealand tax payment"]], ["acc", ["ACC levy New Zealand payment", "Accident Compensation Corporation NZ levy"]]],
  ["BR", "LATAM", "BRL", ["receita", ["Receita Federal Brazil tax payment", "RFB Brasil tax"]], ["inss", ["INSS Brazil contribution", "Instituto Nacional Seguro Social Brasil"]]],
  ["TR", "EUR", "TRY", ["gib", ["Revenue Administration Turkey tax", "GIB Turkey tax payment"]], ["sgk", ["SGK Turkey social security contribution", "Sosyal Guvenlik Kurumu payment"]]],
  ["IE", "EUR", "EUR", ["revenue", ["Revenue Commissioners Ireland tax", "Irish Revenue tax payment"]], ["prsi", ["PRSI Ireland contribution", "Department Social Protection Ireland payment"]]],
  ["CH", "EUR", "CHF", ["fta", ["Federal Tax Administration Switzerland", "Swiss FTA tax payment"]], ["ahv", ["AHV AVS Switzerland contribution", "Swiss old age insurance contribution"]]],
  ["DE", "EUR", "EUR", ["bzst", ["Federal Central Tax Office Germany", "BZSt Germany tax payment"]], ["drv", ["Deutsche Rentenversicherung contribution", "German pension insurance payment"]]],
  ["ES", "EUR", "EUR", ["aeat", ["Agencia Tributaria Spain tax payment", "AEAT Spain tax"]], ["tgss", ["Tesoreria General Seguridad Social Spain", "TGSS Spain contribution"]]],
  ["IT", "EUR", "EUR", ["agenzia", ["Agenzia Entrate Italy tax payment", "Italian Revenue Agency tax"]], ["inps", ["INPS Italy social contribution", "Istituto Nazionale Previdenza Sociale payment"]]],
  ["FR", "EUR", "EUR", ["dgfip", ["DGFiP France tax payment", "Direction Generale Finances Publiques France"]], ["urssaf", ["URSSAF France social contribution", "URSSAF cotisations payment"]]],
  ["PT", "EUR", "EUR", ["at", ["Autoridade Tributaria Portugal payment", "AT Portugal tax"]], ["seguranca-social", ["Seguranca Social Portugal contribution", "Portuguese Social Security payment"]]],
  ["CZ", "EUR", "CZK", ["financni", ["Financial Administration Czech Republic tax", "Financni sprava Czechia payment"]], ["cssa", ["CSSA Czech Republic contribution", "Czech Social Security Administration"]]],
  ["IL", "MEA", "ILS", ["ita", ["Israel Tax Authority payment", "ITA Israel tax"]], ["btl", ["Bituach Leumi Israel contribution", "National Insurance Institute Israel"]]],
  ["JO", "MEA", "JOD", ["istd", ["Income Sales Tax Department Jordan", "ISTD Jordan tax payment"]], ["ssc", ["Social Security Corporation Jordan contribution", "SSC Jordan payment"]]],
  ["OM", "MEA", "OMR", ["tax-authority", ["Tax Authority Oman payment", "Oman Tax Authority tax"]], ["spf", ["Social Protection Fund Oman contribution", "SPF Oman social insurance"]]],
  ["BH", "MEA", "BHD", ["nbr", ["National Bureau Revenue Bahrain tax", "NBR Bahrain payment"]], ["sio", ["Social Insurance Organization Bahrain", "SIO Bahrain contribution"]]],
  ["ET", "AFR", "ETB", ["mor", ["Ministry Revenues Ethiopia tax", "Ethiopian Ministry Revenue payment"]], ["psssa", ["Public Servants Social Security Ethiopia", "PSSSA Ethiopia contribution"]]],
  ["MU", "AFR", "MUR", ["mra", ["Mauritius Revenue Authority tax", "MRA Mauritius payment"]], ["csg", ["Contribution Sociale Generalisee Mauritius", "MRA CSG Mauritius contribution"]]],
  ["BW", "AFR", "BWP", ["burs", ["Botswana Unified Revenue Service tax", "BURS Botswana payment"]], ["bpopf", ["Botswana Public Officers Pension Fund", "BPOPF Botswana contribution"]]],
  ["RS", "EUR", "RSD", ["tax-administration", ["Tax Administration Serbia payment", "Poreska uprava Serbia tax"]], ["pio", ["PIO Fund Serbia contribution", "Republic Pension Disability Fund Serbia"]]],
  ["BA", "EUR", "BAM", ["ita", ["Indirect Taxation Authority Bosnia", "UIO Bosnia tax payment"]], ["fpio", ["Pension Disability Insurance Institute Bosnia", "FPIO Bosnia contribution"]]],
  ["MK", "EUR", "MKD", ["pro", ["Public Revenue Office North Macedonia", "PRO Macedonia tax payment"]], ["piom", ["PIOM North Macedonia contribution", "Pension Disability Insurance Macedonia"]]],
  ["AL", "EUR", "ALL", ["gdt", ["General Directorate Taxation Albania", "Albania tax administration payment"]], ["issh", ["Social Insurance Institute Albania", "ISSH Albania contribution"]]],
  ["MD", "EUR", "MDL", ["sts", ["State Tax Service Moldova payment", "Serviciul Fiscal Moldova tax"]], ["cnas", ["CNAS Moldova contribution", "National Social Insurance House Moldova"]]],
  ["UA", "EUR", "UAH", ["sts", ["State Tax Service Ukraine payment", "Ukrainian Tax Service tax"]], ["pfu", ["Pension Fund Ukraine contribution", "PFU Ukraine payment"]]],
  ["GE", "EUR", "GEL", ["revenue-service", ["Revenue Service Georgia tax", "Georgia Ministry Finance revenue payment"]], ["pension-agency", ["Pension Agency Georgia contribution", "Georgian funded pension payment"]]],
  ["AM", "EUR", "AMD", ["src", ["State Revenue Committee Armenia", "SRC Armenia tax payment"]], ["uss", ["Unified Social Service Armenia contribution", "Armenia social security payment"]]],
  ["AZ", "EUR", "AZN", ["sts", ["State Tax Service Azerbaijan payment", "Azerbaijan Ministry Economy tax"]], ["sspf", ["State Social Protection Fund Azerbaijan", "SSPF Azerbaijan contribution"]]],
  ["IS", "EUR", "ISK", ["skatturinn", ["Iceland Revenue Customs tax", "Skatturinn Iceland payment"]], ["social-insurance", ["Social Insurance Administration Iceland", "Tryggingastofnun Iceland contribution"]]],
  ["LU", "EUR", "EUR", ["acd", ["Administration Contributions Directes Luxembourg", "ACD Luxembourg tax payment"]], ["ccss", ["CCSS Luxembourg contribution", "Joint Social Security Centre Luxembourg"]]],
  ["NI", "LATAM", "NIO", ["dgi", ["DGI Nicaragua tax payment", "Direccion General Ingresos Nicaragua"]], ["inss", ["INSS Nicaragua contribution", "Instituto Nicaraguense Seguridad Social"]]],
  ["JM", "CAR", "JMD", ["taj", ["Tax Administration Jamaica payment", "TAJ Jamaica tax"]], ["nis", ["National Insurance Scheme Jamaica contribution", "NIS Jamaica payment"]]],
  ["TT", "CAR", "TTD", ["bir", ["Board Inland Revenue Trinidad Tobago", "BIR Trinidad tax payment"]], ["nibtt", ["National Insurance Board Trinidad Tobago", "NIBTT contribution"]]],
  ["PG", "OCE", "PGK", ["irc", ["Internal Revenue Commission Papua New Guinea", "IRC PNG tax payment"]], ["nasfund", ["Nasfund Papua New Guinea contribution", "PNG superannuation contribution"]]],
  ["MZ", "AFR", "MZN", ["at", ["Autoridade Tributaria Mozambique", "AT Mozambique tax payment"]], ["inss", ["INSS Mozambique contribution", "Instituto Nacional Seguranca Social Mozambique"]]],
  ["KG", "CAS", "KGS", ["sts", ["State Tax Service Kyrgyzstan payment", "Kyrgyz Republic tax service"]], ["social-fund", ["Social Fund Kyrgyz Republic contribution", "Kyrgyzstan social insurance payment"]]],
  ["MN", "CAS", "MNT", ["gdt", ["General Department Taxation Mongolia", "Mongolia tax administration payment"]], ["sigo", ["Social Insurance General Office Mongolia", "Mongolia social insurance contribution"]]],
  ["VE", "LATAM", "VES", ["seniat", ["SENIAT Venezuela tax payment", "Servicio Administracion Tributaria Venezuela"]], ["ivss", ["IVSS Venezuela contribution", "Instituto Venezolano Seguros Sociales"]]],
  ["BB", "CAR", "BBD", ["bra", ["Barbados Revenue Authority tax", "BRA Barbados payment"]], ["nisss", ["National Insurance Social Security Barbados", "NISSS Barbados contribution"]]],
  ["BS", "CAR", "BSD", ["dir", ["Department Inland Revenue Bahamas", "Bahamas tax payment DIR"]], ["nib", ["National Insurance Board Bahamas", "NIB Bahamas contribution"]]],
  ["FJ", "OCE", "FJD", ["frcs", ["Fiji Revenue Customs Service tax", "FRCS Fiji payment"]], ["fnpf", ["Fiji National Provident Fund contribution", "FNPF Fiji payment"]]],
];

export const WORLD_FISCAL_CONTEXT_ENTRIES_2: ContextEntry[] = PACKS.flatMap((pack) => [
  entry(pack, pack[3], "tax"),
  entry(pack, pack[4], "government_contribution"),
]);
