import type { ContextEntry, RegionalParsingProfile } from "@/lib/context-corpus";

type Country = { code: string; region: string; currency: string };

const rail = (country: Country, id: string, aliases: string[], paymentRail: string, confidence = 82): ContextEntry => ({
  id: `${country.code.toLowerCase()}-${id}`,
  aliases,
  signalKind: "payment_rail",
  countryCode: country.code,
  regionCode: country.region,
  paymentRail,
  institutionType: "wallet",
  currency: country.currency,
  counterpartyType: "wallet",
  purposeHint: "transfer",
  confidence,
});

const bank = (country: Country, id: string, aliases: string[], confidence = 80): ContextEntry => ({
  id: `${country.code.toLowerCase()}-${id}`,
  aliases,
  signalKind: "institution",
  countryCode: country.code,
  regionCode: country.region,
  institutionType: "bank",
  currency: country.currency,
  counterpartyType: "financial_institution",
  confidence,
});

const merchant = (
  country: Country,
  id: string,
  aliases: string[],
  categoryHint: string,
  purposeHint: NonNullable<ContextEntry["purposeHint"]>,
  counterpartyType: NonNullable<ContextEntry["counterpartyType"]> = "merchant",
  confidence = 78,
): ContextEntry => ({
  id: `${country.code.toLowerCase()}-${id}`,
  aliases,
  signalKind: purposeHint === "travel" ? "travel" : "merchant",
  countryCode: country.code,
  regionCode: country.region,
  currency: country.currency,
  categoryHint,
  purposeHint,
  counterpartyType,
  travelLikely: purposeHint === "travel" || purposeHint === "transport",
  confidence,
});

const countries = {
  EE: { code: "EE", region: "EUR", currency: "EUR" },
  LV: { code: "LV", region: "EUR", currency: "EUR" },
  LT: { code: "LT", region: "EUR", currency: "EUR" },
  SK: { code: "SK", region: "EUR", currency: "EUR" },
  SI: { code: "SI", region: "EUR", currency: "EUR" },
  RS: { code: "RS", region: "EUR", currency: "RSD" },
  BA: { code: "BA", region: "EUR", currency: "BAM" },
  MK: { code: "MK", region: "EUR", currency: "MKD" },
  AL: { code: "AL", region: "EUR", currency: "ALL" },
  MD: { code: "MD", region: "EUR", currency: "MDL" },
  UA: { code: "UA", region: "EUR", currency: "UAH" },
  GE: { code: "GE", region: "EUR", currency: "GEL" },
  AM: { code: "AM", region: "EUR", currency: "AMD" },
  AZ: { code: "AZ", region: "EUR", currency: "AZN" },
  CY: { code: "CY", region: "EUR", currency: "EUR" },
  MT: { code: "MT", region: "EUR", currency: "EUR" },
  IS: { code: "IS", region: "EUR", currency: "ISK" },
  LU: { code: "LU", region: "EUR", currency: "EUR" },
  BO: { code: "BO", region: "LATAM", currency: "BOB" },
  PY: { code: "PY", region: "LATAM", currency: "PYG" },
  HN: { code: "HN", region: "LATAM", currency: "HNL" },
  SV: { code: "SV", region: "LATAM", currency: "USD" },
  NI: { code: "NI", region: "LATAM", currency: "NIO" },
  JM: { code: "JM", region: "CAR", currency: "JMD" },
  TT: { code: "TT", region: "CAR", currency: "TTD" },
  DZ: { code: "DZ", region: "AFR", currency: "DZD" },
  TN: { code: "TN", region: "AFR", currency: "TND" },
  ZM: { code: "ZM", region: "AFR", currency: "ZMW" },
  MW: { code: "MW", region: "AFR", currency: "MWK" },
  MZ: { code: "MZ", region: "AFR", currency: "MZN" },
  KZ: { code: "KZ", region: "CAS", currency: "KZT" },
  UZ: { code: "UZ", region: "CAS", currency: "UZS" },
  KG: { code: "KG", region: "CAS", currency: "KGS" },
  MN: { code: "MN", region: "EAS", currency: "MNT" },
} satisfies Record<string, Country>;

const { EE, LV, LT, SK, SI, RS, BA, MK, AL, MD, UA, GE, AM, AZ, CY, MT, IS, LU, BO, PY, HN, SV, NI, JM, TT, DZ, TN, ZM, MW, MZ, KZ, UZ, KG, MN } = countries;

/**
 * Second reviewed worldwide pack. Ambiguous brands are always qualified by
 * country or city. Rails provide provenance and never assert an expense or an
 * own-account transfer on their own.
 */
export const WORLD_CONTEXT_ENTRIES_2: ContextEntry[] = [
  // Baltics and Central Europe.
  rail(EE, "rt1", ["rt1 instant payment estonia", "sepa instant estonia"], "estonia_sepa_instant", 88),
  bank(EE, "swedbank", ["swedbank estonia", "swedbank eesti"]),
  merchant(EE, "tallinn-transit", ["tallinna linnatransport", "uhiskaart tallinn"], "Transport", "transport", "transport_provider"),
  merchant(EE, "selver", ["selver estonia", "selver eesti"], "Groceries", "groceries", "grocer"),
  merchant(EE, "energia", ["eesti energia", "enefit estonia electricity"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(LV, "instant", ["zibmaksajums latvia", "instant payment latvia"], "latvia_instant_payment", 88),
  bank(LV, "citadele", ["citadele banka latvia", "citadele latvija"]),
  merchant(LV, "rigas-satiksme", ["rigas satiksme", "rīgas satiksme"], "Transport", "transport", "transport_provider"),
  merchant(LV, "rimi", ["rimi latvia", "rimi latvija"], "Groceries", "groceries", "grocer"),
  merchant(LV, "latvenergo", ["latvenergo latvia", "elektrum latvija"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(LT, "centrolink", ["centrolink lithuania", "momentinis mokejimas lietuva"], "lithuania_centrolink", 90),
  bank(LT, "siauliu", ["siauliu bankas lithuania", "šiaulių bankas"]),
  merchant(LT, "vilnius-transit", ["vilniecio kortele", "vilniečio kortelė"], "Transport", "transport", "transport_provider"),
  merchant(LT, "maxima", ["maxima lithuania", "maxima lietuva"], "Groceries", "groceries", "grocer"),
  merchant(LT, "ignitis", ["ignitis lithuania", "ignitis lietuva"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(SK, "instant", ["sepa instant slovakia", "okamzita platba slovensko"], "slovakia_sepa_instant", 88),
  bank(SK, "tatra", ["tatra banka slovakia", "tatra banka slovensko"]),
  merchant(SK, "ids-bk", ["ids bk bratislava", "integrovany dopravny system bratislava"], "Transport", "transport", "transport_provider"),
  merchant(SK, "billa", ["billa slovakia", "billa slovensko"], "Groceries", "groceries", "grocer"),
  merchant(SK, "zse", ["zse energia slovakia", "zapadoslovenska energetika"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(SI, "flik", ["flik slovenia", "flik placilo slovenija"], "slovenia_flik", 88),
  bank(SI, "nlb", ["nova ljubljanska banka", "nlb slovenia"]),
  merchant(SI, "urbana", ["urbana ljubljana", "lpp urbana slovenia"], "Transport", "transport", "transport_provider"),
  merchant(SI, "mercator", ["mercator slovenia", "mercator slovenija"], "Groceries", "groceries", "grocer"),
  merchant(SI, "elektro", ["elektro ljubljana", "elektro energija slovenia"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(RS, "ips", ["ips nbs serbia", "instant placanje srbija"], "serbia_ips", 90),
  bank(RS, "intesa", ["banca intesa serbia", "banca intesa srbija"]),
  merchant(RS, "beograd-plus", ["beograd plus karta", "busplus beograd"], "Transport", "transport", "transport_provider"),
  merchant(RS, "maxi", ["maxi supermarket serbia", "maxi srbija"], "Groceries", "groceries", "grocer"),
  merchant(RS, "eps", ["elektroprivreda srbije", "eps struja serbia"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(BA, "raiffeisen", ["raiffeisen bank bosnia", "raiffeisen bih"]),
  bank(BA, "unicredit", ["unicredit bank bosnia", "unicredit bih"]),
  merchant(BA, "gras", ["gras sarajevo", "javni prijevoz sarajevo gras"], "Transport", "transport", "transport_provider"),
  merchant(BA, "bingo", ["bingo supermarket bosnia", "bingo bih"], "Groceries", "groceries", "grocer"),
  merchant(BA, "epbih", ["elektroprivreda bih", "ep bih electricity"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(MK, "komercijalna", ["komercijalna banka north macedonia", "комерцијална банка македонија"]),
  bank(MK, "halkbank", ["halkbank north macedonia", "халкбанк македонија"]),
  merchant(MK, "jsp", ["jsp skopje", "јсп скопје"], "Transport", "transport", "transport_provider"),
  merchant(MK, "vero", ["vero market north macedonia", "веро маркет македонија"], "Groceries", "groceries", "grocer"),
  merchant(MK, "evn", ["evn north macedonia", "евни македонија струја"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(AL, "bkt", ["banka kombetare tregtare", "bkt albania"]),
  bank(AL, "raiffeisen", ["raiffeisen bank albania", "raiffeisen shqiperi"]),
  merchant(AL, "tirana-transit", ["tirana public transport", "transporti urban tirane"], "Transport", "transport", "transport_provider"),
  merchant(AL, "big-market", ["big market albania", "big market shqiperi"], "Groceries", "groceries", "grocer"),
  merchant(AL, "oshee", ["oshee albania", "operatori shperndarjes energjise elektrike"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MD, "mia", ["mia plati instant moldova", "mia instant payments moldova"], "moldova_mia", 88),
  bank(MD, "maib", ["maib moldova", "moldova agroindbank"]),
  merchant(MD, "trolleybus", ["regia transport electric chisinau", "troleibuz chisinau"], "Transport", "transport", "transport_provider"),
  merchant(MD, "linella", ["linella moldova", "linella chisinau"], "Groceries", "groceries", "grocer"),
  merchant(MD, "premier-energy", ["premier energy moldova", "premier energy chisinau"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(UA, "sep", ["sep nbu ukraine", "сеп нбу україна"], "ukraine_sep", 86),
  bank(UA, "privatbank", ["privatbank ukraine", "приватбанк україна"]),
  merchant(UA, "kyiv-digital", ["kyiv digital transport", "київ цифровий транспорт"], "Transport", "transport", "transport_provider"),
  merchant(UA, "silpo", ["silpo ukraine", "сільпо україна"], "Groceries", "groceries", "grocer"),
  merchant(UA, "yasno", ["yasno electricity ukraine", "ясно електроенергія"], "Bills & Utilities", "utilities", "utility_provider"),

  // Caucasus, Mediterranean, and smaller European markets.
  bank(GE, "bog", ["bank of georgia", "საქართველოს ბანკი"]),
  bank(GE, "tbc", ["tbc bank georgia", "თიბისი ბანკი"]),
  merchant(GE, "tbilisi-transit", ["tbilisi transport company", "თბილისის სატრანსპორტო კომპანია"], "Transport", "transport", "transport_provider"),
  merchant(GE, "carrefour", ["carrefour georgia", "კარფური საქართველო"], "Groceries", "groceries", "grocer"),
  merchant(GE, "telasi", ["telasi georgia electricity", "თელასი თბილისი"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(AM, "arca", ["arca armenia payment", "arca card armenia"], "armenia_arca", 84),
  bank(AM, "ameriabank", ["ameriabank armenia", "ամերիաբանկ", "ԱՄԵՐԻԱԲԱՆԿ"]),
  merchant(AM, "yerevan-metro", ["yerevan metro", "երևանի մետրոպոլիտեն", "ԵՐԵՎԱՆԻ ՄԵՏՐՈՊՈԼԻՏԵՆ"], "Transport", "transport", "transport_provider"),
  merchant(AM, "yerevan-city", ["yerevan city supermarket", "երևան սիթի սուպերմարկետ", "ԵՐԵՎԱՆ ՍԻԹԻ ՍՈՒՊԵՐՄԱՐԿԵՏ"], "Groceries", "groceries", "grocer"),
  merchant(AM, "ena", ["electric networks of armenia", "հայաստանի էլեկտրական ցանցեր", "ՀԱՅԱՍՏԱՆԻ ԷԼԵԿՏՐԱԿԱՆ ՑԱՆՑԵՐ"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(AZ, "azericard", ["azericard azerbaijan", "azericard azərbaycan"], "azerbaijan_azericard", 84),
  bank(AZ, "kapital", ["kapital bank azerbaijan", "kapital bank azərbaycan"]),
  merchant(AZ, "baku-card", ["baku card transport", "bakikart azerbaijan"], "Transport", "transport", "transport_provider"),
  merchant(AZ, "bravo", ["bravo supermarket azerbaijan", "bravo market baku"], "Groceries", "groceries", "grocer"),
  merchant(AZ, "azerishiq", ["azerishiq electricity", "azərişıq", "AZƏRIŞIQ"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(CY, "jcc", ["jcc payment systems cyprus", "jccsmart cyprus"], "cyprus_jcc", 84),
  bank(CY, "boc", ["bank of cyprus", "τραπεζα κυπρου"]),
  merchant(CY, "motion", ["motion bus cyprus", "cyprus public transport motion"], "Transport", "transport", "transport_provider"),
  merchant(CY, "alphamega", ["alphamega hypermarkets cyprus", "αλφαμεγα κυπρος"], "Groceries", "groceries", "grocer"),
  merchant(CY, "eac", ["electricity authority of cyprus", "αηκ κυπρος"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MT, "bov-pay", ["bov pay malta", "bank of valletta mobile pay"], "malta_bov_pay", 82),
  bank(MT, "bov", ["bank of valletta malta", "bov malta"]),
  merchant(MT, "tallinja", ["tallinja malta", "malta public transport tallinja"], "Transport", "transport", "transport_provider"),
  merchant(MT, "welbees", ["welbees supermarket malta", "welbee's malta"], "Groceries", "groceries", "grocer"),
  merchant(MT, "enemalta", ["enemalta electricity", "enemalta malta"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(IS, "aur", ["aur app iceland", "aur greiðslur island"], "iceland_aur", 82),
  bank(IS, "landsbankinn", ["landsbankinn iceland", "landsbankinn island"]),
  merchant(IS, "straeto", ["straeto iceland", "strætó bs"], "Transport", "transport", "transport_provider"),
  merchant(IS, "bonus", ["bonus supermarket iceland", "bónus island"], "Groceries", "groceries", "grocer"),
  merchant(IS, "veitur", ["veitur utilities iceland", "veitur ohf"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(LU, "payconiq", ["payconiq luxembourg", "digicash payconiq luxembourg"], "luxembourg_payconiq", 86),
  bank(LU, "spuerkeess", ["spuerkeess luxembourg", "banque et caisse epargne etat luxembourg"]),
  merchant(LU, "mobiliteit", ["mobiliteit luxembourg", "mobiliteitszentral luxembourg"], "Transport", "transport", "transport_provider"),
  merchant(LU, "cactus", ["cactus supermarket luxembourg", "cactus luxembourg grocery"], "Groceries", "groceries", "grocer"),
  merchant(LU, "enovos", ["enovos luxembourg", "enovos energie luxembourg"], "Bills & Utilities", "utilities", "utility_provider"),

  // Latin America and the Caribbean.
  rail(BO, "simple", ["simple pagos bolivia", "qr simple bolivia"], "bolivia_qr", 84),
  bank(BO, "bisa", ["banco bisa bolivia", "bisa bolivia"]),
  merchant(BO, "mi-teleferico", ["mi teleferico bolivia", "teleferico la paz"], "Transport", "transport", "transport_provider"),
  merchant(BO, "hipermaxi", ["hipermaxi bolivia", "hiper maxi bolivia"], "Groceries", "groceries", "grocer"),
  merchant(BO, "delapaz", ["delapaz electricidad bolivia", "distribuidora electricidad la paz"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(PY, "spi", ["spi paraguay pagos instantaneos", "sipap paraguay"], "paraguay_spi", 88),
  bank(PY, "continental", ["banco continental paraguay", "continental paraguay banco"]),
  merchant(PY, "jaha", ["tarjeta jaha paraguay", "jaha transporte paraguay"], "Transport", "transport", "transport_provider"),
  merchant(PY, "stock", ["supermercado stock paraguay", "stock supermercados paraguay"], "Groceries", "groceries", "grocer"),
  merchant(PY, "ande", ["ande paraguay electricidad", "administracion nacional electricidad paraguay"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(HN, "tengo", ["tengo honduras wallet", "tengo dinero honduras"], "honduras_wallet", 82),
  bank(HN, "ficohsa", ["banco ficohsa honduras", "ficohsa honduras"]),
  merchant(HN, "rapidito", ["transporte rapidito honduras", "rapiditos tegucigalpa"], "Transport", "transport", "transport_provider"),
  merchant(HN, "la-colonia", ["supermercados la colonia honduras", "la colonia honduras supermercado"], "Groceries", "groceries", "grocer"),
  merchant(HN, "enee", ["enee honduras", "empresa nacional energia electrica honduras"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(SV, "transfer365", ["transfer365 el salvador", "transfer 365 banco central reserva"], "el_salvador_transfer365", 90),
  bank(SV, "agricola", ["banco agricola el salvador", "banco agrícola salvador"]),
  merchant(SV, "sitramss", ["sitramss el salvador", "sistema integrado transporte salvador"], "Transport", "transport", "transport_provider"),
  merchant(SV, "super-selectos", ["super selectos el salvador", "selectos supermercado salvador"], "Groceries", "groceries", "grocer"),
  merchant(SV, "caess", ["caess el salvador electricidad", "aes caess salvador"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(NI, "banpro", ["banpro nicaragua", "banco produccion nicaragua"]),
  bank(NI, "lafise", ["bancentro lafise nicaragua", "banco lafise nicaragua"]),
  merchant(NI, "tuc", ["tarjeta tuc nicaragua", "transporte urbano colectivo managua"], "Transport", "transport", "transport_provider"),
  merchant(NI, "la-union", ["supermercado la union nicaragua", "la unión nicaragua supermercado"], "Groceries", "groceries", "grocer"),
  merchant(NI, "disnorte", ["disnorte dissur nicaragua", "naturgy nicaragua electricidad"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(JM, "jamdex", ["jam dex jamaica", "jam-dex jamaica digital currency"], "jamaica_jamdex", 88),
  bank(JM, "ncb", ["national commercial bank jamaica", "ncb jamaica"]),
  merchant(JM, "jutc", ["jamaica urban transit company", "jutc jamaica"], "Transport", "transport", "transport_provider"),
  merchant(JM, "hi-lo", ["hi lo food stores jamaica", "hi-lo jamaica supermarket"], "Groceries", "groceries", "grocer"),
  merchant(JM, "jps", ["jamaica public service", "jps electricity jamaica"], "Bills & Utilities", "utilities", "utility_provider"),
  bank(TT, "republic", ["republic bank trinidad tobago", "republic bank tt"]),
  bank(TT, "first-citizens", ["first citizens bank trinidad", "first citizens tt"]),
  merchant(TT, "ptsc", ["public transport service corporation trinidad", "ptsc trinidad"], "Transport", "transport", "transport_provider"),
  merchant(TT, "mass-y", ["mass y stores trinidad", "massystores trinidad"], "Groceries", "groceries", "grocer"),
  merchant(TT, "ttech", ["trinidad tobago electricity commission", "t and tec trinidad"], "Bills & Utilities", "utilities", "utility_provider"),

  // North, Southern, and East Africa.
  rail(DZ, "baridimob", ["baridimob algeria", "بريدي موب الجزائر"], "algeria_baridimob", 84),
  bank(DZ, "bna", ["banque nationale algerie", "البنك الوطني الجزائري"]),
  merchant(DZ, "metro", ["metro alger algeria", "مترو الجزائر"], "Transport", "transport", "transport_provider"),
  merchant(DZ, "uno", ["uno hypermarket algeria", "uno algerie hypermarche"], "Groceries", "groceries", "grocer"),
  merchant(DZ, "sonelgaz", ["sonelgaz algeria", "سونلغاز الجزائر"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(TN, "d17", ["d17 poste tunisienne", "d17 tunisia wallet"], "tunisia_d17", 84),
  bank(TN, "biat", ["biat tunisia", "banque internationale arabe tunisie"]),
  merchant(TN, "transtu", ["transtu tunis", "societe transports tunis"], "Transport", "transport", "transport_provider"),
  merchant(TN, "mg", ["magasin general tunisie", "mg supermarket tunisia"], "Groceries", "groceries", "grocer"),
  merchant(TN, "steg", ["steg tunisie", "societe tunisienne electricite gaz"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(ZM, "mtn-momo", ["mtn mobile money zambia", "mtn momo zambia"], "zambia_mobile_money", 84),
  bank(ZM, "zanaco", ["zanaco bank zambia", "zambia national commercial bank"]),
  merchant(ZM, "ubz", ["united bus zambia", "ubz bus zambia"], "Transport", "transport", "transport_provider"),
  merchant(ZM, "shoprite", ["shoprite zambia", "shoprite supermarket zambia"], "Groceries", "groceries", "grocer"),
  merchant(ZM, "zesco", ["zesco zambia", "zesco electricity zambia"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MW, "airtel-money", ["airtel money malawi", "airtel malawi mobile money"], "malawi_mobile_money", 84),
  bank(MW, "nbm", ["national bank of malawi", "nbm malawi"]),
  merchant(MW, "axxes", ["axxes bus malawi", "axxes coaches malawi"], "Transport", "transport", "transport_provider"),
  merchant(MW, "peoples", ["peoples supermarket malawi", "peoples trading centre malawi"], "Groceries", "groceries", "grocer"),
  merchant(MW, "escom", ["escom malawi", "electricity supply corporation malawi"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MZ, "mpesa", ["m-pesa mozambique", "mpesa mocambique"], "mozambique_mobile_money", 86),
  bank(MZ, "bim", ["millennium bim mozambique", "banco internacional mocambique"]),
  merchant(MZ, "chapas", ["chapas maputo mozambique", "transporte chapa mocambique"], "Transport", "transport", "transport_provider"),
  merchant(MZ, "shoprite", ["shoprite mozambique", "shoprite mocambique"], "Groceries", "groceries", "grocer"),
  merchant(MZ, "edm", ["electricidade de mocambique", "edm mozambique electricity"], "Bills & Utilities", "utilities", "utility_provider"),

  // Central and East Asia.
  rail(KZ, "instant", ["instant payment system kazakhstan", "система мгновенных платежей казахстан"], "kazakhstan_instant_payment", 86),
  bank(KZ, "kaspi", ["kaspi bank kazakhstan", "каспи банк казахстан"]),
  merchant(KZ, "onay", ["onay transport almaty", "онай алматы транспорт"], "Transport", "transport", "transport_provider"),
  merchant(KZ, "magnum", ["magnum supermarket kazakhstan", "магнум казахстан"], "Groceries", "groceries", "grocer"),
  merchant(KZ, "alatau", ["alatau zharyk company", "алатау жарық компаниясы"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(UZ, "humo", ["humo payment uzbekistan", "humo tolov uzbekiston"], "uzbekistan_humo", 86),
  bank(UZ, "kapitalbank", ["kapitalbank uzbekistan", "капиталбанк узбекистан"]),
  merchant(UZ, "atto", ["atto transport tashkent", "atto toshkent transport"], "Transport", "transport", "transport_provider"),
  merchant(UZ, "korzinka", ["korzinka uzbekistan", "korzinka uzbekiston"], "Groceries", "groceries", "grocer"),
  merchant(UZ, "hududiy", ["hududiy elektr tarmoqlari", "regional electric networks uzbekistan"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(KG, "elqr", ["elqr kyrgyzstan", "элкарт qr кыргызстан"], "kyrgyzstan_elqr", 86),
  bank(KG, "demir", ["demirbank kyrgyzstan", "демир банк кыргызстан"]),
  merchant(KG, "tulpar", ["tulpar card bishkek", "тулпар карта бишкек"], "Transport", "transport", "transport_provider"),
  merchant(KG, "globus", ["globus supermarket kyrgyzstan", "глобус кыргызстан супермаркет"], "Groceries", "groceries", "grocer"),
  merchant(KG, "severelectro", ["severelectro kyrgyzstan", "северэлектро кыргызстан"], "Bills & Utilities", "utilities", "utility_provider"),
  rail(MN, "qpay", ["qpay mongolia", "qpay монгол"], "mongolia_qpay", 86),
  bank(MN, "khan", ["khan bank mongolia", "хаан банк монгол"]),
  merchant(MN, "ub-smart", ["ub smart card mongolia", "улаанбаатар смарт карт"], "Transport", "transport", "transport_provider"),
  merchant(MN, "nomin", ["nomin supermarket mongolia", "номин супермаркет монгол"], "Groceries", "groceries", "grocer"),
  merchant(MN, "ubedn", ["ulaanbaatar electricity distribution", "улаанбаатар цахилгаан түгээх"], "Bills & Utilities", "utilities", "utility_provider"),
];

const profile = (
  countryCode: string,
  regionCode: string,
  locales: string[],
  languages: string[],
  dateOrder: RegionalParsingProfile["dateOrder"],
  decimalSeparator: RegionalParsingProfile["decimalSeparator"],
  groupingSeparator: RegionalParsingProfile["groupingSeparator"],
  defaultCurrency: string,
  legalEntitySuffixes: string[],
  confidence = 70,
): RegionalParsingProfile => ({
  countryCode, regionCode, locales, primaryLocale: locales[0], languages, dateOrder,
  decimalSeparator, groupingSeparator, defaultCurrency, legalEntitySuffixes, confidence,
});

export const WORLD_REGIONAL_PROFILES_2: RegionalParsingProfile[] = [
  profile("EE", "EUR", ["et-EE", "en-EE"], ["et", "en"], "dmy", ",", " ", "EUR", ["ou", "as", "tuh"], 76),
  profile("LV", "EUR", ["lv-LV", "en-LV"], ["lv", "en"], "dmy", ",", " ", "EUR", ["sia", "as", "ik"], 76),
  profile("LT", "EUR", ["lt-LT", "en-LT"], ["lt", "en"], "dmy", ",", " ", "EUR", ["uab", "ab", "mb"], 76),
  profile("SK", "EUR", ["sk-SK", "en-SK"], ["sk", "en"], "dmy", ",", " ", "EUR", ["sro", "as", "ks"], 76),
  profile("SI", "EUR", ["sl-SI", "en-SI"], ["sl", "en"], "dmy", ",", ".", "EUR", ["doo", "dd", "sp"], 74),
  profile("RS", "EUR", ["sr-RS", "en-RS"], ["sr", "en"], "dmy", ",", ".", "RSD", ["doo", "ad", "preduzetnik"], 74),
  profile("BA", "EUR", ["bs-BA", "hr-BA", "sr-BA"], ["bs", "hr", "sr"], "dmy", ",", ".", "BAM", ["doo", "dd", "ad"], 70),
  profile("MK", "EUR", ["mk-MK", "sq-MK", "en-MK"], ["mk", "sq", "en"], "dmy", ",", ".", "MKD", ["doo", "dooel", "ad"], 70),
  profile("AL", "EUR", ["sq-AL", "en-AL"], ["sq", "en"], "dmy", ",", ".", "ALL", ["shpk", "sha", "person fizik"], 70),
  profile("MD", "EUR", ["ro-MD", "ru-MD", "en-MD"], ["ro", "ru", "en"], "dmy", ",", " ", "MDL", ["srl", "sa", "ii"], 72),
  profile("UA", "EUR", ["uk-UA", "en-UA"], ["uk", "en"], "dmy", ",", " ", "UAH", ["tov", "at", "pat"], 76),
  profile("GE", "EUR", ["ka-GE", "en-GE"], ["ka", "en"], "dmy", ".", ",", "GEL", ["llc", "jsc", "ltd"], 72),
  profile("AM", "EUR", ["hy-AM", "en-AM"], ["hy", "en"], "dmy", ".", ",", "AMD", ["llc", "cjsc", "ojsc"], 72),
  profile("AZ", "EUR", ["az-AZ", "en-AZ"], ["az", "en"], "dmy", ",", " ", "AZN", ["mmc", "asc", "qsc"], 72),
  profile("CY", "EUR", ["el-CY", "tr-CY", "en-CY"], ["el", "tr", "en"], "dmy", ".", ",", "EUR", ["ltd", "plc", "limited"], 72),
  profile("MT", "EUR", ["mt-MT", "en-MT"], ["mt", "en"], "dmy", ".", ",", "EUR", ["ltd", "plc", "limited"], 72),
  profile("IS", "EUR", ["is-IS", "en-IS"], ["is", "en"], "dmy", ",", ".", "ISK", ["ehf", "hf", "ohf"], 74),
  profile("LU", "EUR", ["fr-LU", "de-LU", "lb-LU"], ["fr", "de", "lb"], "dmy", ",", ".", "EUR", ["sarl", "sa", "sca"], 74),
  profile("BO", "LATAM", ["es-BO", "en-BO"], ["es", "en"], "dmy", ",", ".", "BOB", ["sa", "srl", "unipersonal"], 70),
  profile("PY", "LATAM", ["es-PY", "gn-PY"], ["es", "gn"], "dmy", ",", ".", "PYG", ["sa", "srl", "eas"], 72),
  profile("HN", "LATAM", ["es-HN", "en-HN"], ["es", "en"], "dmy", ".", ",", "HNL", ["sa", "s de rl", "limitada"], 68),
  profile("SV", "LATAM", ["es-SV", "en-SV"], ["es", "en"], "dmy", ".", ",", "USD", ["sa de cv", "limitada", "srl"], 72),
  profile("NI", "LATAM", ["es-NI", "en-NI"], ["es", "en"], "dmy", ".", ",", "NIO", ["sa", "srl", "compania limitada"], 68),
  profile("JM", "CAR", ["en-JM"], ["en"], "dmy", ".", ",", "JMD", ["ltd", "limited", "plc"], 72),
  profile("TT", "CAR", ["en-TT"], ["en"], "dmy", ".", ",", "TTD", ["ltd", "limited", "plc"], 68),
  profile("DZ", "AFR", ["ar-DZ", "fr-DZ"], ["ar", "fr"], "dmy", ",", " ", "DZD", ["sarl", "spa", "eurl"], 72),
  profile("TN", "AFR", ["ar-TN", "fr-TN"], ["ar", "fr"], "dmy", ",", " ", "TND", ["sarl", "sa", "suarl"], 72),
  profile("ZM", "AFR", ["en-ZM"], ["en"], "dmy", ".", ",", "ZMW", ["ltd", "limited", "plc"], 70),
  profile("MW", "AFR", ["en-MW", "ny-MW"], ["en", "ny"], "dmy", ".", ",", "MWK", ["ltd", "limited", "plc"], 68),
  profile("MZ", "AFR", ["pt-MZ", "en-MZ"], ["pt", "en"], "dmy", ",", ".", "MZN", ["lda", "sa", "unipessoal"], 68),
  profile("KZ", "CAS", ["kk-KZ", "ru-KZ"], ["kk", "ru"], "dmy", ",", " ", "KZT", ["too", "ao", "ip"], 74),
  profile("UZ", "CAS", ["uz-UZ", "ru-UZ"], ["uz", "ru"], "dmy", ",", " ", "UZS", ["mchj", "aj", "xk"], 72),
  profile("KG", "CAS", ["ky-KG", "ru-KG"], ["ky", "ru"], "dmy", ",", " ", "KGS", ["osoo", "ao", "ip"], 70),
  profile("MN", "EAS", ["mn-MN", "en-MN"], ["mn", "en"], "ymd", ".", ",", "MNT", ["xxk", "xk", "tukhk"], 70),
];
