import Link from "next/link";
import type { AdminOperationsSnapshot } from "@/lib/admin-operations";

export function AdminOperationsConsole({ snapshot }: { snapshot: AdminOperationsSnapshot }) {
  return (
    <div className="admin-operations">
      <section className="admin-operations__alerts table-panel" id="alerts">
        <div className="admin-users__table-head"><div><p className="eyebrow">Alerts</p><h3>What needs attention</h3></div><span className="panel-muted">Updated {new Date(snapshot.generatedAt).toLocaleString("en-PH")}</span></div>
        <div className="admin-operations__alert-list">{snapshot.alerts.map((alert) => <Link key={alert.title} className={`admin-operations__alert admin-operations__alert--${alert.severity}`} href={alert.href}><strong>{alert.title}</strong><span>{alert.detail}</span></Link>)}</div>
      </section>
      <div className="admin-operations__grid">
        <section className="table-panel" id="billing"><div className="admin-users__table-head"><div><p className="eyebrow">Billing support</p><h3>Subscription health</h3></div><Link className="button button-secondary button-small" href="/admin/users">Open users</Link></div><div className="admin-operations__metrics"><div><strong>{snapshot.billing.active}</strong><span>Active</span></div><div><strong>{snapshot.billing.pending}</strong><span>Pending</span></div><div><strong>{snapshot.billing.cancelled}</strong><span>Cancelled</span></div><div><strong>{snapshot.billing.suspended}</strong><span>Suspended</span></div></div><div className="admin-operations__event-list">{snapshot.billing.recentEvents.map((event) => <div key={event.id}><strong>{event.eventType}</strong><span>{event.userEmail ?? "Unmatched user"} · {new Date(event.createdAt).toLocaleString("en-PH")}</span></div>)}{snapshot.billing.recentEvents.length === 0 ? <p className="panel-muted">No billing events in the last 7 days.</p> : null}</div></section>
        <section className="table-panel" id="imports"><div className="admin-users__table-head"><div><p className="eyebrow">Import operations</p><h3>Processing health</h3></div><Link className="button button-secondary button-small" href="/admin/data-qa">Open Data QA</Link></div><div className="admin-operations__metrics"><div><strong>{snapshot.imports.processing}</strong><span>Processing</span></div><div><strong>{snapshot.imports.stale}</strong><span>Stale</span></div><div><strong>{snapshot.imports.failed24h}</strong><span>Failed 24h</span></div><div><strong>{snapshot.imports.queuedJobs}</strong><span>Queued jobs</span></div></div><div className="admin-operations__event-list">{snapshot.imports.recent.map((item) => <div key={item.id}><strong>{item.fileName}</strong><span>{item.status} · {item.phase ?? "No phase"} · {item.userEmail}</span></div>)}{snapshot.imports.recent.length === 0 ? <p className="panel-muted">No active or recently failed imports.</p> : null}</div></section>
        <section className="table-panel" id="access"><div className="admin-users__table-head"><div><p className="eyebrow">Admin access</p><h3>Access configuration</h3></div><span className="admin-users__pill admin-users__pill--success">{snapshot.access.environment}</span></div><p className="panel-muted">{snapshot.access.note}</p><div className="admin-operations__access-list"><div><strong>Admin emails</strong><span>{snapshot.access.configuredAdminEmails.join(", ") || "None configured"}</span></div><div><strong>Admin user IDs</strong><span>{snapshot.access.adminUserIds.join(", ") || "None configured"}</span></div><div><strong>Admin-only IDs</strong><span>{snapshot.access.configuredAdminOnlyIds.join(", ") || "None configured"}</span></div></div></section>
        <section className="table-panel"><div className="admin-users__table-head"><div><p className="eyebrow">Support governance</p><h3>Recovery and activity</h3></div><Link className="button button-secondary button-small" href="/admin/support">Open Support</Link></div><div className="admin-operations__metrics"><div><strong>{snapshot.support.actions24h}</strong><span>Actions 24h</span></div><div><strong>{snapshot.support.notes7d}</strong><span>Notes 7d</span></div><div><strong>{snapshot.support.snapshotsAvailable}</strong><span>Recovery snapshots</span></div></div><div className="admin-operations__event-list">{snapshot.support.recentActions.map((action) => <div key={action.id}><strong>{action.action}</strong><span>{action.targetEmail ?? "Unknown user"} · {new Date(action.createdAt).toLocaleString("en-PH")}</span></div>)}{snapshot.support.recentActions.length === 0 ? <p className="panel-muted">No support actions recorded yet.</p> : null}</div></section>
      </div>
    </div>
  );
}
