"use client";
import { useEffect,useState } from "react";
import styles from "./switch-campaign.module.css";
type Application={id:string;user:{email:string;planTier:string};status:string;claimBy:string|null;expiresAt:string|null;activatedAt:string|null;convertedAt:string|null;duplicateEvidence:boolean;evidence:{id:string;fileName:string;purgedAt:string|null}[];events:{id:string;kind:string;message:string;emailStatus:string;createdAt:string}[]};
type Data={role:string;config:{status:string;capacity:number;redeemedCount:number;endsAt:string|null};applications:Application[]};
export function AdminSwitchCampaign(){const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState("draft"),[ends,setEnds]=useState(""),[reason,setReason]=useState(""),[replies,setReplies]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/admin/campaigns/switch-to-clover",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error);setData(p);setStatus(p.config.status);setEnds(p.config.endsAt?new Date(p.config.endsAt).toISOString().slice(0,16):"");}
 useEffect(()=>{void load().catch(e=>setMessage(e.message));},[]);
 async function act(body:unknown){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/campaigns/switch-to-clover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error);await load();setMessage("Saved.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
 const editable=data?.role==="owner"||data?.role==="admin";
 const reserved=data?.applications.filter(a=>a.status==="approved"&&a.claimBy&&new Date(a.claimBy)>new Date()).length??0;
 return <section className={styles.card}><h2>Switch to Clover · Receipt campaign</h2><p>30 days of complimentary Plus · Seven-day claim reservations · No payment details required.</p><a href="/offers/switch-to-clover" target="_blank" rel="noreferrer">Preview offer</a><p role="status">{message}</p>
 {data?<><p>{data.applications.length} applications · {reserved} awaiting activation · {data.config.redeemedCount} redeemed · {data.applications.filter(a=>a.convertedAt).length} converted</p><form className={styles.form} onSubmit={e=>{e.preventDefault();void act({action:"configure",status,endsAt:ends?new Date(ends+"Z").toISOString():null,reason});}}><label>Status<select value={status} disabled={!editable} onChange={e=>setStatus(e.target.value)}>{["draft","active","paused","ended"].map(s=><option key={s}>{s}</option>)}</select></label><label>End date in UTC (blank = no scheduled end)<input type="datetime-local" value={ends} disabled={!editable} onChange={e=>setEnds(e.target.value)}/></label><label>Reason for configuration change<input value={reason} required minLength={3} maxLength={500} disabled={!editable} onChange={e=>setReason(e.target.value)}/></label><button className="button button-primary" disabled={busy||!editable}>Save campaign</button></form><p>Pausing or ending closes new applications. Existing approvals and rewards remain valid. Review complete applications in submission order.</p>
 {data.applications.map(a=><article key={a.id} className={styles.card}><h3>{a.user.email}</h3><p>{a.status} · {a.activatedAt?"Reward redeemed":"Not yet redeemed"}{a.claimBy?` · Claim by ${new Date(a.claimBy).toLocaleString()}`:""}{a.expiresAt?` · Reward ends ${new Date(a.expiresAt).toLocaleString()}`:""}</p>{a.duplicateEvidence?<p className={styles.error}>Duplicate evidence appears on another application. Review before approving.</p>:null}<div className={styles.actions}>{a.evidence.map(e=>e.purgedAt||data.role==="read_only"?<span key={e.id}>{e.purgedAt?"Evidence purged":"Private evidence"}</span>:<a key={e.id} href={`/api/campaigns/evidence?id=${e.id}`} target="_blank" rel="noreferrer">View {e.fileName}</a>)}</div><ol>{a.events.map(e=><li key={e.id}>{e.message}<br/><small>{new Date(e.createdAt).toLocaleString()} · Email: {e.emailStatus}</small></li>)}</ol>{["submitted","needs_information"].includes(a.status)&&editable?<><label>Message to applicant<textarea maxLength={2000} value={replies[a.id]??""} onChange={e=>setReplies({...replies,[a.id]:e.target.value})}/></label><div className={styles.actions}>{(["approved","rejected","needs_information"] as const).map(decision=><button key={decision} disabled={busy||!replies[a.id]?.trim()} onClick={()=>void act({action:"review",id:a.id,decision,message:replies[a.id]})}>{decision==="approved"?"Approve":decision==="rejected"?"Reject":"Request information"}</button>)}</div></>:null}</article>)}{!data.applications.length?<p>No applications yet.</p>:null}</>:null}</section>;
}
