"use client";
import {useEffect,useState} from 'react';
import type {BankLifecycleView} from '../../shared/finverse-lifecycle-view';
export function FinverseLifecyclePanel({workspaceId}:{workspaceId:string}) {
 const [revision,setRevision]=useState(0);
 useEffect(()=>{const refresh=()=>setRevision(n=>n+1);window.addEventListener('finverse-updated',refresh);return()=>window.removeEventListener('finverse-updated',refresh);},[]);
 const [data,setData]=useState<BankLifecycleView|null>(null),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();setData(null);setSelected([]);fetch(`/api/integrations/finverse/connections?workspaceId=${encodeURIComponent(workspaceId)}`,{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(!c.signal.aborted){setData(d.lifecycle);setSelected(d.lifecycle.connections.flatMap((c:BankLifecycleView['connections'][number])=>c.accounts.filter(a=>a.retained&&!a.unlinkedAt&&c.status!=='disconnect_pending'&&c.status!=='disconnected').map(a=>a.id)));}}).catch(()=>{if(!c.signal.aborted)setMessage('Unable to load connected banks. Please retry.');});return()=>c.abort();},[workspaceId,revision]);
 if(!data)return message?<p role="status">{message} <button onClick={()=>{setMessage('');setRevision(n=>n+1);}}>Retry</button></p>:null;
 if(!data.connections.length)return null;
 const save=async()=>{setBusy(true);try{const r=await fetch('/api/integrations/finverse/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,retainIds:selected})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Saved. These accounts are preferred if your plan changes to Plus.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}};
 return <details className="finverse-connect__selection"><summary>Manage connected banks</summary><p>Your plan allows {data.limit} linked accounts. Choose up to two to retain on Plus; otherwise the most recently synced accounts are retained. Free disconnects all banks when paid access ends.</p>{data.accessEndsAt?<p role="status">Paid access ends {new Date(data.accessEndsAt).toLocaleDateString()}.</p>:null}<p>Connections without a successful sync for 90 days are disconnected after advance warnings. Financial history stays. A bank login shared by retained and excess accounts must be disconnected and reconnected with your chosen accounts.</p>{data.connections.map(c=><fieldset key={c.id}><legend>{c.name} · {c.status==='disconnect_pending'?'Disconnection pending':c.status==='disconnected'?'Disconnected':'Connected'}</legend><p>Last synced {c.lastSyncedAt?new Date(c.lastSyncedAt).toLocaleString():'Never'}{c.status!=='disconnected'?` · Inactivity deadline ${new Date(c.inactivityDeadline).toLocaleDateString()}`:''}</p>{c.disconnectReason?<p>{c.disconnectReason}</p>:null}{c.disconnectError?<p role="status">{c.disconnectError}</p>:null}{c.accounts.filter(a=>a.accountId).map(a=><label key={a.id} style={{display:'block'}}><input type="checkbox" disabled={busy||!!a.unlinkedAt||c.status==='disconnect_pending'||c.status==='disconnected'||(!selected.includes(a.id)&&selected.length>=2)} checked={selected.includes(a.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,a.id]:s.filter(id=>id!==a.id))}/>{a.name} · Keep on Plus</label>)}</fieldset>)}<button className="button button-secondary" disabled={busy} onClick={()=>void save()}>Save retained accounts</button>{message?<p role="status">{message}</p>:null}</details>;
}
