import { selectExistingClerkSession } from "../lib/clerk-initial-session";
import assert from "node:assert/strict";
import { adviserCurrency, adviserMonthRange, isSpendingSummaryQuestion, commitmentInstallment } from "../lib/adviser-analysis";
import { classifyAdviserScope } from "../lib/adviser-scope";
import { classifyEverydayQuestion, isEverydayFollowUp } from "../lib/adviser-everyday";
import { selectAdviserToolNames } from "../lib/adviser-tool-routing";
import { readAiConsent } from "../lib/ai-consent-request";
import { resolveCircleMemberPhoto } from "../lib/circle-member-photo-match";
import { buildBudgetOverview } from "../lib/budgeting";
async function main() {
  for(const q of ["What is an emergency fund?","Check upcoming bills","Explain compound interest","List overdue payments"]) assert(classifyAdviserScope(q).allowed,q);
  assert.equal(classifyEverydayQuestion("What is an emergency fund?"), null);
  assert.deepEqual(selectAdviserToolNames({question:"What is an emergency fund?"}), []);
  assert.equal(isEverydayFollowUp("What is an emergency fund?"), false);
  assert.equal(isEverydayFollowUp("Check upcoming bills"), false);
  assert.equal(isEverydayFollowUp("PHP 25,000"), true);
  assert.equal(isEverydayFollowUp("Yes"), true);
  const routine = "What is a simple weekly routine for keeping track of several bank accounts, a credit card, and e-wallets?";
  assert.equal(classifyEverydayQuestion(routine),null);
  assert.deepEqual(selectAdviserToolNames({question:routine}),[]);
  assert.equal(classifyEverydayQuestion("What credit card can I get?"),"credit_card");
  assert(isSpendingSummaryQuestion("Show my PHP spending by category for September 2026. Focus only on expenses, excluding transfers."));
  assert.equal(isSpendingSummaryQuestion("How much did I spend at Starbucks in September?"),false);
  assert.equal(isSpendingSummaryQuestion("Compare food spending this month"),false);
  assert.equal(adviserCurrency("My USD spending",["PHP","USD"]),"USD");
  assert.equal(adviserCurrency("My spending",["USD","PHP"]),"PHP");
  const now = new Date("2026-09-29T04:00:00Z");
  const range=adviserMonthRange("September 2026",now)!;
  assert.equal(range.start.toISOString(),"2026-09-01T00:00:00.000Z");
  assert.equal(range.end.toISOString(),"2026-10-01T00:00:00.000Z");
  assert.equal(adviserMonthRange("last month",new Date("2026-01-15"))!.label,"December 2025");
  assert.equal(commitmentInstallment({kind:"debt",amount:1749000,tracking:{paymentAmount:15000}}),15000);
  assert.equal(commitmentInstallment({kind:"debt",amount:1749000}),0);
  const transactions=[{currency:"PHP",amount:100,date:new Date("2026-09-01")},{currency:"USD",amount:500,date:now},{currency:"PHP",amount:700,date:new Date("2026-08-31")}].map(t=>({...t,accountId:"a",categoryId:"food",type:"expense" as const,isExcluded:false}));
  const budgets=buildBudgetOverview({now,budgets:[{id:"b",name:"Food",kind:"spend_limit",scope:"category",cadence:"monthly",targetAmount:200,currency:"PHP",isActive:true,accountId:null,categoryId:"food"}],transactions}).budgets;
  assert.equal(budgets[0].actualAmount,100);assert.equal(budgets[0].remainingAmount,100);
  const member={userId:"u",displayName:"Alex Reyes"};
  assert.equal(resolveCircleMemberPhoto(member,[{name:"Alex Reyes",avatarUrl:"shared.jpg"}],new Map([["u","profile.jpg"]])),"profile.jpg");
  assert.equal(resolveCircleMemberPhoto({...member,userId:null},[{name:" Alex Reyes ",avatarUrl:"shared.jpg"}],new Map()),"shared.jpg");
  assert.equal(resolveCircleMemberPhoto(member,[],new Map()),null);
  assert.equal(resolveCircleMemberPhoto(member,[{name:"Alex Reyes",avatarUrl:"a"},{name:"Alex Reyes",avatarUrl:"b"}],new Map()),null);
  const client = {sessions:[{id:"older"},{id:"active"}],lastActiveSessionId:"active"};
  assert.equal(selectExistingClerkSession(client,"")?.id,"active");
  assert.equal(selectExistingClerkSession(client,"older")?.id,"older");
  assert.equal(selectExistingClerkSession(client,"expired")?.id,"active");
  assert.equal(selectExistingClerkSession({sessions:[],lastActiveSessionId:null}),null);
  let calls=0;
  assert.deepEqual(await readAiConsent(async()=>{calls++;return calls===1?new Response(null,{status:503}):Response.json({allowed:true});}),{allowed:true});assert.equal(calls,2);
  calls=0;await assert.rejects(readAiConsent(async()=>{calls++;return new Response(null,{status:401});}),/session/);assert.equal(calls,1);
  await assert.rejects(readAiConsent(async()=>new Response(null,{status:503})),/Unable/);
  assert.deepEqual(await readAiConsent(async()=>Response.json({allowed:false})),{allowed:false});
  await assert.rejects(readAiConsent(async()=>Response.json({allowed:"true"})),/Invalid/);
  console.log("Adviser reliability and Circle photos passed: scope, intent, month/currency boundaries, installments, budget arithmetic, identity matching and fail-closed consent retries.");
}
void main().catch(e=>{console.error(e);process.exitCode=1;});
