import assert from 'node:assert/strict';
import {planBankReconciliation} from '../lib/finverse-reconciliation';
import {bankNumbersMatch} from '../lib/finverse-matching';
import {mergeAccountsWithOptimisticImports,mergeProvisionalAccountSnapshot} from '../lib/imported-account-ui';
assert.equal(bankNumbersMatch('123-4-567-89012-3','123XXXXXX0123'),true);
assert.equal(bankNumbersMatch('1234567890123','7890123'),false);
const account={id:'a',name:'Metrobank',institution:'Metrobank',type:'bank',currency:'PHP',source:'upload',balance:'73095.69'};
const bank={...account,bankBalance:'45613.63',bankBalanceAt:'2026-09-24T12:00:00Z',balance:'45613.63'};
assert.equal(mergeAccountsWithOptimisticImports([bank],[account],{preferCurrentImportedSnapshot:true})[0].balance,'45613.63');
assert.equal(mergeAccountsWithOptimisticImports([{...bank,bankBalance:'0'}],[account],{preserveNonZeroOptimisticBalance:true})[0].balance,'0');
assert.equal(mergeProvisionalAccountSnapshot([bank],[account],new Set())[0].bankBalance,'45613.63');
const row={id:'old',date:'2026-09-01',amount:'100',currency:'PHP',type:'expense',reviewStatus:'edited',isExcluded:false,deletedAt:null};
const incoming={...row,id:'bank',reviewStatus:'suggested',type:'income'};
const original=JSON.stringify(row);
assert.equal(planBankReconciliation([incoming],[row])[0].needsReview,true);
assert.equal(JSON.stringify(row),original);
assert.equal(planBankReconciliation([{...incoming,amount:'200'}],[row])[0].needsReview,false);
assert.throws(()=>planBankReconciliation([row],[]));
console.log('Bank reconciliation: masked identity, snapshot precedence, zero balance, overlap review and confirmed-edit preservation passed.');
