import assert from "node:assert/strict";
import { emptyTransactionFilters, transactionFilterQuery, matchesDemoFilters } from "../../mobile/src/transaction-filter-query";
import { parseTransactionQueryFilters } from "../lib/transaction-query";
import { transactionReviewReasons } from "../../mobile/src/transaction-review";
const filters = { ...emptyTransactionFilters, types: ["debit", "transfer"], accounts: ["bank-a", "bank-b"], categories: ["groceries"], tags: ["family", "work"], currency: "PHP", amountMin: "10", amountMax: "100", dateFilterMode: "custom", customStart: "2026-09-01", customEnd: "2026-09-30", sourceFilter: "manual", confidenceFilter: "high", reviewFilter: "pending" };
const parsed = parseTransactionQueryFilters(new URLSearchParams(transactionFilterQuery(filters)));
assert.deepEqual(parsed.accountIds, filters.accounts);
assert.deepEqual(parsed.categoryIds, filters.categories);
assert.deepEqual(parsed.tagIds, filters.tags);
assert.deepEqual(parsed.typeFilters, filters.types);
assert.equal(parsed.currencyFilter, "PHP");
for (const key of ["amountMin", "amountMax", "dateFilterMode", "customStart", "customEnd", "sourceFilter", "confidenceFilter", "reviewFilter"] as const) assert.equal(parsed[key], filters[key]);
const row = { id:"one",workspaceId:"profile",accountId:"bank-a",accountName:"Bank",date:"2026-09-20",amount:"-50",currency:"PHP",type:"expense" as const,merchantRaw:"Shop",merchantClean:"Shop",description:null,categoryName:"Groceries",categoryId:"groceries",confidenceScore:0.95,reviewStatus:"pending_review",reviewReasons:["Needs account review"],source:"manual",tags:[{id:"family",name:"Family"}] };
assert.equal(matchesDemoFilters(row, filters), true);
assert.equal(matchesDemoFilters({...row,currency:"USD"},filters),false);
assert.equal(matchesDemoFilters({...row,amount:"200"},filters),false);
assert.equal(matchesDemoFilters({...row,accountId:"other"},filters),false);
assert.equal(matchesDemoFilters({...row,reviewStatus:"confirmed"},filters),false);
assert.equal(matchesDemoFilters({...row,date:"2026-08-31"},filters),false);
assert.equal(matchesDemoFilters({...row,confidenceScore:null},filters),false);
assert.equal(matchesDemoFilters(row,emptyTransactionFilters),true);
assert.equal(matchesDemoFilters({...row,reviewReasons:[]},filters),false);
assert.equal(matchesDemoFilters({...row,reviewStatus:"edited"},filters),false);
const { reviewReasons: _reasons, ...legacy } = row;
assert.deepEqual(transactionReviewReasons(legacy), [], "A clean legacy pending suggestion is not a warning.");
assert.deepEqual(transactionReviewReasons({...legacy,isExcluded:true}), ["Ignored from totals"]);
assert.deepEqual(transactionReviewReasons({...legacy,categoryName:null,categoryId:null}), ["Needs category review"]);
assert.deepEqual(transactionReviewReasons({...legacy,confidenceScore:0.5}), ["Check the transaction details against the original file."]);
assert.deepEqual(transactionReviewReasons({...legacy,confidenceScore:50}), ["Check the transaction details against the original file."]);
assert.deepEqual(transactionReviewReasons({...legacy,merchantClean:null,merchantRaw:""}), ["Could not identify merchant"]);
assert.deepEqual(transactionReviewReasons({...legacy,isExcluded:true,reviewReasons:[]}), [], "Explicit new server projections override legacy inference.");
assert.deepEqual(transactionReviewReasons({...legacy,isExcluded:true,reviewStatus:"confirmed"}), [], "Confirmed cached data remains resolved.");
assert.deepEqual(transactionReviewReasons({reviewStatus:"pending_review"}), [], "Absent cached facts do not invent warnings.");
console.log("Native transaction filters preserve all desktop query fields and demo filtering semantics.");
