import assert from "node:assert/strict";
import { emptyTransactionFilters, transactionFilterQuery, matchesDemoFilters } from "../../mobile/src/transaction-filter-query";
import { parseTransactionQueryFilters } from "../lib/transaction-query";
const filters = { ...emptyTransactionFilters, types: ["debit", "transfer"], accounts: ["bank-a", "bank-b"], categories: ["groceries"], tags: ["family", "work"], currency: "PHP", amountMin: "10", amountMax: "100", dateFilterMode: "custom", customStart: "2026-09-01", customEnd: "2026-09-30", sourceFilter: "manual", confidenceFilter: "high", reviewFilter: "pending" };
const parsed = parseTransactionQueryFilters(new URLSearchParams(transactionFilterQuery(filters)));
assert.deepEqual(parsed.accountIds, filters.accounts);
assert.deepEqual(parsed.categoryIds, filters.categories);
assert.deepEqual(parsed.tagIds, filters.tags);
assert.deepEqual(parsed.typeFilters, filters.types);
assert.equal(parsed.currencyFilter, "PHP");
for (const key of ["amountMin", "amountMax", "dateFilterMode", "customStart", "customEnd", "sourceFilter", "confidenceFilter", "reviewFilter"] as const) assert.equal(parsed[key], filters[key]);
const row = { id:"one",workspaceId:"profile",accountId:"bank-a",accountName:"Bank",date:"2026-09-20",amount:"-50",currency:"PHP",type:"expense" as const,merchantRaw:"Shop",merchantClean:"Shop",description:null,categoryName:"Groceries",categoryId:"groceries",confidenceScore:0.95,reviewStatus:"pending_review",source:"manual",tags:[{id:"family",name:"Family"}] };
assert.equal(matchesDemoFilters(row, filters), true);
assert.equal(matchesDemoFilters({...row,currency:"USD"},filters),false);
assert.equal(matchesDemoFilters({...row,amount:"200"},filters),false);
assert.equal(matchesDemoFilters({...row,accountId:"other"},filters),false);
assert.equal(matchesDemoFilters({...row,reviewStatus:"confirmed"},filters),false);
assert.equal(matchesDemoFilters({...row,date:"2026-08-31"},filters),false);
assert.equal(matchesDemoFilters({...row,confidenceScore:null},filters),false);
assert.equal(matchesDemoFilters(row,emptyTransactionFilters),true);
console.log("Native transaction filters preserve all desktop query fields and demo filtering semantics.");
