import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildOnboardingMissions, type OnboardingMissionId } from "../../shared/onboarding-missions";
import { buildHomeNextSteps } from "../lib/home-next-steps";
const none: Record<OnboardingMissionId, boolean> = { add_account:false, add_transaction:false, set_budget:false, create_goal:false, ask_clover:false };
const empty=buildOnboardingMissions(none);
assert.equal(empty.totalCount,5);
assert.equal(empty.completedCount,0);
assert.equal(empty.nextMission?.id,"add_account");
assert.ok(empty.missions.every(m=>!("description" in m)),"Mission rows are title-only.");
const laterFirst=buildOnboardingMissions({...none,create_goal:true,ask_clover:true});
assert.equal(laterFirst.completedCount,2,"Completed actions count even out of order.");
assert.equal(laterFirst.nextMission?.id,"add_account");
const data=buildOnboardingMissions({...none,add_account:true,add_transaction:true});
assert.equal(data.nextMission?.id,"set_budget");
assert.equal(data.totalCount,5,"No conditional review missions.");
const complete=buildOnboardingMissions({add_account:true,add_transaction:true,set_budget:true,create_goal:true,ask_clover:true});
assert.equal(complete.complete,true);
assert.equal(complete.nextMission,null);
assert.equal(buildOnboardingMissions(none,true).dismissed,true);
const server=readFileSync("lib/onboarding-missions.ts","utf8");
assert.doesNotMatch(server,/\.update\(|\.delete\(|\.create\(/,"Mission derivation remains read-only.");
assert.match(server,/prisma\.transaction\.count\(\{ where: \{ workspaceId, deletedAt: null, isExcluded: false \}/);
assert.doesNotMatch(server,/importFileId: null|source: "manual"/,"All entry methods qualify.");
assert.match(server,/userId: \{ in: actorUserIds \}/,"Questions belong to the current user.");
assert.match(server,/name: \{ not: "Cash" \}/,"Untouched starter Cash is not a user-added account.");
const component=readFileSync("components/onboarding-missions.tsx","utf8");
assert.doesNotMatch(component,/mission\.description|surface === "home"/);
assert.match(readFileSync("components/clover-shell.tsx","utf8"),/OnboardingMissions key=\{searchWorkspaceId\} surface="popover"/);
assert.deepEqual(buildHomeNextSteps({transactionCount:0,recurringCount:0,statementCount:0}),[]);
assert.deepEqual(buildHomeNextSteps({transactionCount:3,recurringCount:2,statementCount:1}).map(({id,count})=>({id,count})),[{id:"transactions",count:3},{id:"recurring",count:2},{id:"statements",count:1}]);
console.log("Onboarding missions regression passed.");
