import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { normalizePlanAnalytics, planContext, publicPlan } from "../../shared/plan-analytics";
import { calculateProAccess } from "../lib/pro-access-rules";
const now = new Date("2026-09-24T00:00:00Z");
const tomorrow = new Date(+now + 86400000), later = new Date(+now + 86400000 * 30);
const base = { planTier: "free" as const, planTierLocked: false, subscription: null, grants: [] };
const plus = { startsAt: now, endsAt: later, revokedAt: null, planTier: "pro" as const };
const pro = { startsAt: now, endsAt: tomorrow, revokedAt: null, planTier: "premium" as const };
assert.equal(calculateProAccess({ ...base, grants: [plus, pro] }, now).planTier, "premium");
assert.equal(calculateProAccess({ ...base, grants: [plus, pro] }, now).accessEndsAt?.toISOString(), tomorrow.toISOString());
assert.equal(calculateProAccess({ ...base, grants: [plus, pro] }, tomorrow).planTier, "pro");
assert.equal(calculateProAccess({ ...base, grants: [plus, pro] }, later).planTier, "free");
assert.equal(calculateProAccess({ ...base, grants: [{ ...pro, revokedAt: now }] }, now).planTier, "free");
assert.equal(calculateProAccess({ ...base, grants: [{ ...pro, startsAt: tomorrow }] }, now).planTier, "free");
const paidPlus = { status: "active", planTier: "pro" as const, interval: "monthly", paidThrough: later };
assert.equal(calculateProAccess({ ...base, subscription: paidPlus, grants: [pro] }, now).accessEndsAt?.toISOString(), tomorrow.toISOString());
assert.equal(calculateProAccess({ ...base, subscription: paidPlus, grants: [pro] }, tomorrow).planTier, "pro");
assert.equal(calculateProAccess({ ...base, subscription: { ...paidPlus, planTier: "premium" }, grants: [plus] }, now).planTier, "premium");
assert.equal(calculateProAccess({ ...base, planTierLocked: true, grants: [pro] }, now).planTier, "free");
assert.equal(calculateProAccess({ ...base, grants: [{ startsAt: now, endsAt: later, revokedAt: null }] }, now).planTier, "pro");
assert.deepEqual([publicPlan("free"), publicPlan("pro"), publicPlan("premium")], ["free", "plus", "pro"]);
const event = normalizePlanAnalytics({ plan_tier: "premium", previous_plan: "pro", platform: "ios" });
assert.equal(event.plan_tier, "pro"); assert.equal(event.previous_plan, "plus"); assert.equal(event.platform, "ios");
assert.deepEqual(normalizePlanAnalytics(event), event);
assert.equal(planContext("pro", "manual override", "paddle", true).is_paid_subscriber, true);
assert.equal(planContext("premium", "complimentary").is_paid_subscriber, false);
const admin = readFileSync("lib/admin-users.ts", "utf8");
const update = admin.slice(admin.indexOf("export async function updateAdminUser"), admin.indexOf("export async function getAdminUserDetail"));
assert.ok(!update.includes("cancelPayPalSubscription"));
assert.ok(!update.includes("tx.billingSubscription.update"));
const endpoint = readFileSync("app/api/admin/users/[userId]/route.ts", "utf8");
assert.ok(endpoint.includes('requireAdminAuth("entitlements")'));
console.log("PASS tiered grants: precedence, expiry, downgrade, revocation, schedules, legacy defaults, paid access preservation; analytics mapping/idempotence/device context; Admin billing isolation and permissions.");
