import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { performance } from "node:perf_hooks";
import { parseImportText } from "@/lib/import-parser";
import { validateImportFileBytes } from "@/lib/import-file-validation";
import { readAppMigration, createMigrationOverlapMatcher } from "@/lib/app-migration-import";
import { enrichParsedRowsWithTraining } from "@/lib/data-engine";

export async function runQifMigrationRegression() {
  const text = readFileSync("scripts/fixtures/app-migrations/qif-multi-account-synthetic.qif", "utf8");
  const parse = (value: string) => parseImportText(value, "history.qif", "application/qif", { currency: "PHP" });
  const rows = parse(text);
  assert.equal(rows.length, 7, "QIF split parts replace totals; opening balance/category definitions are not transactions");
  assert(rows.every(r => readAppMigration(r.rawPayload)?.source === "qif"));
  assert.deepEqual(rows.map(r => r.amount), ["60.00", "40.00", "30.00", "10.00", "2500.00", "40.00", "12.50"]);
  assert.deepEqual(rows.map(r => r.type), ["expense", "transfer", "expense", "income", "income", "transfer", "expense"]);
  assert.deepEqual([...new Set(rows.map(r => r.accountName))], ["QIF Checking", "QIF Savings", "QIF Visa"]);
  assert.equal(rows[6].rawPayload?.accountType, "credit_card");
  assert.equal(rows[0].categoryName, "Food / Groceries");
  assert.equal(rows[0].description, "Weekend purchases · Weekly food");
  assert.deepEqual(readAppMigration(rows[0].rawPayload)?.tags, ["QIF: Household"]);
  assert.equal(rows[1].categoryName, "Transfers");
  assert.equal(rows[1].rawPayload?.parsedDirectionType, "expense");
  assert.equal(rows[5].rawPayload?.parsedDirectionType, "income");
  assert.equal((rows[0].rawPayload?.qifRecord as any).parentAmount, -100);
  assert((rows[0].rawPayload?.qifRecord as any).lines.includes("$-60.00"));
  assert.equal(readAppMigration(rows[0].rawPayload)?.sourceId, "", "A reused check number is not a unique transaction ID");
  const summary = rows[0].rawPayload?.migrationSummary as any;
  assert.equal(summary.inputRows, 6); assert.equal(summary.importedRows, 7); assert.equal(summary.skippedRows.length, 1);
  assert.deepEqual(summary.totals[0], { account: "QIF Checking", currency: "PHP", income: 2510, expense: 90, transferIn: 0, transferOut: 40, excluded: 0, rows: 5 });
  assert.equal(validateImportFileBytes({ fileName: "history.qif", contentType: "application/qif", bytes: new TextEncoder().encode(text) }), null);
  assert.equal(parse(text.replaceAll("\n", "\r")).length, 7);
  assert.equal(validateImportFileBytes({ fileName: "history.qif", contentType: "application/qif", bytes: new TextEncoder().encode(text.replaceAll("\n", "\r")) }), null);
  const single = "!Type:Bank\nD2026-09-13\nT-12.50\nPShop\nLFood\n^";
  const contextual = (value: string) => parseImportText(value, "history.qif", "application/qif", { currency: "USD", accountName: "Checking" });
  assert.equal(contextual(single)[0].accountName, "Checking");
  assert.throws(() => parse(single), /Choose an account/);
  assert.throws(() => parseImportText(text, "history.qif", "application/qif"), /currency/i);
  assert.throws(() => parse(text.replace("$-60.00", "$-59.00")), /split amounts/);
  assert.throws(() => parse(text.replace("$-60.00\n", "")), /amount/i);
  assert.throws(() => parse(text.replace("T-20.00", "T-20.00\nT-30.00")), /Duplicate T/);
  assert.throws(() => parse(text.replace("$-60.00", "$-60.00\n$-60.00")), /duplicate fields/);
  assert.throws(() => parse(text.replace("!Type:CCard", "!Type:Invst")), /Unsupported QIF section/);
  assert.throws(() => parse(text.replace("2026-09-05", "2026-02-30")), /date is invalid/);
  assert.throws(() => contextual(single.replace("2026-09-13", "9/10/2026")), /ambiguous/);
  assert.equal(contextual(single.replace("2026-09-13", "9/13'26"))[0].date, "2026-09-13");
  assert.equal(contextual(single.replace("2026-09-13", "13/9/2026"))[0].date, "2026-09-13");
  assert.equal(contextual(single.replace("2026-09-13", "9/13/97"))[0].date, "1997-09-13");
  assert.throws(() => contextual(single.replace("2026-09-13", "9/13/2026") + "\nD14/9/2026\nT1\nPShop\nLFood\n^"), /mixes day-first/);
  for (const amount of ["-1x2", "-12,34", "-12.345", "--12", "NaN", "1e3", "9007199254740992"]) assert.throws(() => contextual(single.replace("-12.50", amount)), /amount/i);
  assert.throws(() => contextual(single.slice(0, -1)), /terminator/);
  assert.throws(() => contextual(single.replace("T-12.50", "T-12.50\nU-12.51")), /disagree/);
  assert.throws(() => contextual(single.replace("LFood", "L[Other")), /brackets/);
  assert.throws(() => contextual(single.replace("LFood", "L--Split--")), /parts are missing/);
  assert.throws(() => contextual(single.replace("LFood", "LFood\n%50")), /Unsupported transaction field/);
  assert.equal(contextual(single.replace("LFood", "LTransfer fees"))[0].type, "expense");
  assert.throws(() => parse(text.replace("NQIF Checking\nTBank\n^", "NAccount A\nTBank\n^\nNAccount B\nTBank\n^")), /which account/);
  const openingIdentity = "!Type:Bank\nD2026-09-01\nT100\nPOpening Balance\nL[Named Checking]\n^\nD2026-09-02\nT-10\nPShop\nLFood\n^";
  assert.equal(parse(openingIdentity)[0].accountName, "Named Checking");
  assert.deepEqual(parse(openingIdentity + "\n" + openingIdentity.replaceAll("Named Checking", "Other Checking")).map(r => r.accountName), ["Named Checking", "Other Checking"]);
  const zeroNet = "!Type:Bank\nD2026-09-13\nT0\nPRefund exchange\nSFood\n$-10\nSFood\n$10\n^";
  assert.deepEqual(contextual(zeroNet).map(r => r.type), ["expense", "income"]);
  const checkOne = contextual(single.replace("PShop", "PShop\nN1001"));
  const checkTwo = contextual(single.replace("PShop", "PShop\nN1002"));
  assert.equal(createMigrationOverlapMatcher(checkOne.map(r => ({ ...r, accountId: "one" })))({ ...checkTwo[0], accountId: "one" }), false);
  const uncategorized = contextual(single.replace("LFood\n", ""))[0];
  assert.equal(uncategorized.rawPayload?.reviewRequired, true); assert.match(String(uncategorized.rawPayload?.reviewReason), /category/);
  const repeated = parse(text.replace("!Type:Cat", "!Type:CCard\nD2026-09-05\nT-12.50\nPCoffee shop\nLFood:Coffee\n^\n!Type:Cat"));
  assert.equal(repeated.length, 8, "Identical legitimate purchases retain their occurrence count");
  const matcher = createMigrationOverlapMatcher(rows.map(r => ({ ...r, accountId: r.accountName, date: "2020-01-01", amount: "1.00", description: "Confirmed edit" })));
  assert.equal(repeated.filter(r => !matcher({ ...r, accountId: r.accountName })).length, 1);
  const enriched = await enrichParsedRowsWithTraining({ workspaceId: "offline-qif", rows });
  assert.deepEqual(enriched.map(r => [r.amount, r.type, r.categoryName, r.description]), rows.map(r => [r.amount, r.type, r.categoryName, r.description]));
  const large = "!Account\nNQIF Large\nTBank\n^\n!Type:Bank\n" + Array.from({ length: 3000 }, (_, i) => `D2026-09-01\nT-50\nPShop ${i}\nSFood\n$-30\nSTravel\n$-20\n^`).join("\n");
  const start = performance.now();
  const largeRows = await enrichParsedRowsWithTraining({ workspaceId: "offline-qif-large", rows: parse(large) });
  const ms = Math.round(performance.now() - start);
  assert.equal(largeRows.length, 6000); assert.equal(largeRows.reduce((s, r) => s + Number(r.amount), 0), 150000);
  assert(ms < 10000, `QIF 3,000 split records exceeded 10 seconds: ${ms}`);
  console.log(`PASS QIF: multi-account, splits, transfer directions, raw evidence, invalid-file rejection, confirmed reimports; 3,000 split records / 6,000 rows in ${ms}ms`);
}
