import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { incompleteReceiptFields, receiptCurrencyForPersistence, receiptReviewMessage, RECEIPT_REVIEW_PHASE } from "../lib/receipt-review";
import { buildImportTelemetrySnapshot } from "../lib/import-telemetry";
import { resolveImportModalStatusDecision } from "../lib/import-modal-status";
import { mobileApiResponse } from "../lib/mobile-api-response";
import { enforceRegionalReceiptCurrencyEvidence, hasRegionalReceiptCurrencyEvidence } from "../lib/receipt-currency-evidence";
import { assessReceiptCoreMoney, enforceReceiptCoreMerchantEvidence } from "../lib/receipt-core-evidence";

const complete = { merchant_raw: "상점", merchant_clean: null, transaction_date: "2026-09-30", currency: "KRW", total: 60000 };
assert.deepEqual(incompleteReceiptFields(complete), []);
assert.deepEqual(incompleteReceiptFields({ ...complete, merchant_raw: null, transaction_date: null, currency: null }), ["merchant", "date", "currency"]);
assert.deepEqual(incompleteReceiptFields({ ...complete, transaction_date: "2026-02-30" }), ["date"]);
assert.deepEqual(incompleteReceiptFields({ ...complete, total: NaN, currency: "MIXED" }), ["currency", "total"]);
assert.deepEqual(incompleteReceiptFields({ ...complete, total: 0 }), ["total"]);
assert.equal(receiptCurrencyForPersistence(null), "MIXED", "Do not assign PHP to an unknown receipt currency");
assert.equal(receiptCurrencyForPersistence("TL"), "MIXED", "A total label is not an ISO currency");
assert.equal(receiptCurrencyForPersistence("IDR"), "IDR");
assert.equal(receiptCurrencyForPersistence("KRW"), "KRW");
assert.equal(hasRegionalReceiptCurrencyEvidence("KRW", "회원 직원 합계 60,000"), false);
assert.equal(hasRegionalReceiptCurrencyEvidence("KRW", "정상과세판매가(3,120원)"), true);
assert.equal(hasRegionalReceiptCurrencyEvidence("KRW", "총 합계 157,600 원"), true);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "GRAND TOTAL 61,799 TUNAI 62,000"), false);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "Total Rp125.000"), true);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "Total Rp 125.000,50"), true);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "GRAND TOTAL 61,799\nRp"), false);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "Rp\n61,799"), false, "An isolated symbol is not a quoted monetary line");
const inferred = { currency: "KRW", confidence_score: .98, parser_evidence: { reason: "Korean merchant", source_text: "합계 60,000" } };
assert.equal(enforceRegionalReceiptCurrencyEvidence(inferred).currency, null);
assert.equal(enforceRegionalReceiptCurrencyEvidence(inferred).confidence_score, .5);
assert.equal(inferred.currency, "KRW", "Keep original AI evidence unchanged for audit");
assert.equal(enforceRegionalReceiptCurrencyEvidence({ ...inferred, currency_source_text: "60,000원" }).currency, "KRW");
const money = (total: number, source_text: string) => assessReceiptCoreMoney({ total, parser_evidence: { source_text, reason: "Image evidence" } });
assert.equal(money(48, "GRAND TOTAL 48.000\nTUNAI 50.000\nKEMBALI 2.000").details.total, 48000);
assert.equal(money(49, "GRAND TOTAL 49.000\nTUNAI 50.000\nKEMBALI 2.000").needsReread, true);
assert.equal(money(49, "GRAND TOTAL 49.000\nTUNAI 50.000\nKEMBALI 2.000").details.total, null, "Do not invent a total from tender/change when printed evidence conflicts");
assert.equal(money(62000, "GRAND TOTAL 61,799\nTUNAI 62,000\nKEMBALI 201").details.total, 61799);
assert.equal(money(14, "TL . 14,000\nCASH . 20,000\nCG . 6,000").details.total, 14000);
assert.equal(money(14.5, "TOTAL USD14.50\nCASH USD20.00\nCHANGE USD5.50").details.total, 14.5, "Do not apply the integer guard to explicit foreign-currency decimals");
assert.equal(money(1250000.5, "GRAND TOTAL Rp1.250.000,50\nTUNAI Rp1.300.000,00\nKEMBALI Rp49.999,50").details.total, 1250000.5);
assert.equal(money(1250000.5, "GRAND TOTAL IDR1,250,000.50\nCASH IDR1,300,000.00\nCHANGE IDR49,999.50").needsReread, false);
assert.equal(money(14000, "TL .14,000\nCASH .20,000\nCG .1,000").needsReread, true);
assert.equal(money(48000, "GRAND TOTAL 48.000\nTUNAI 48.000\nKEMBALI 0").needsReread, false);
assert.equal(money(48000, "GRAND TOTAL 48.000\nTUNAI 50.000\nTUNAI 60.000\nKEMBALI 2.000").needsReread, true);
const itemName = { merchant_raw: "SYNTHETIC CHOCOLATE", merchant_clean: "Synthetic Chocolate", merchant_source_text: "SYNTHETIC CHOCOLATE 14,000", merchant_source_kind: "product_line" };
assert.equal(enforceReceiptCoreMerchantEvidence(itemName).merchant_raw, null);
assert.equal(itemName.merchant_raw, "SYNTHETIC CHOCOLATE", "Preserve original model evidence");
assert.equal(enforceReceiptCoreMerchantEvidence({ ...itemName, merchant_source_kind: "business_logo", merchant_source_text: "Toko QA", merchant_raw: "Toko QA" }).merchant_raw, "Toko QA");
assert.deepEqual(incompleteReceiptFields({ ...complete, merchant_raw: " ", merchant_clean: "Toko", currency: "IDR" }), []);
const message = receiptReviewMessage(["date"]);
assert.match(message, /Review the date/);
assert.doesNotMatch(message, /upload|reupload/i, "Partial receipts should invite completing the saved draft");
const snapshot = { status: "failed", processingPhase: RECEIPT_REVIEW_PHASE, processingMessage: message, workflowStage: "identifying_transactions", parsedRowsCount: 0, confirmedTransactionsCount: 0 };
const telemetry = buildImportTelemetrySnapshot(snapshot);
assert.equal(telemetry.canResume, false, "Missing source fields must not trigger repeated provider calls");
assert.equal(telemetry.phase, "repair_needed");
assert.equal(telemetry.message, message);
assert.equal(resolveImportModalStatusDecision({ ...snapshot, importMode: "receipt", telemetryPhase: telemetry.phase }).kind, "repair_needed");
assert.equal(resolveImportModalStatusDecision({ ...snapshot, importMode: "receipt", confirmedTransactionsCount: 1 }).kind, "visible", "Existing committed transactions retain visibility");
assert.equal(buildImportTelemetrySnapshot({ status: "processing", processingPhase: "queued_retry" }).canResume, true, "Transient failures remain recoverable");
const mobile = mobileApiResponse("import-status", { importFile: snapshot, confirmedTransactionsCount: 0, parsedRowsCount: 0, visibleImportComplete: false });
assert.equal((mobile.importFile as typeof snapshot).processingMessage, message);
assert.equal((mobile.importFile as typeof snapshot).status, "failed");
assert.equal(mobile.visibleImportComplete, false);
const worker = readFileSync("workers/import-processor.ts", "utf8");
assert.ok(worker.indexOf("const missingReceiptFields =") < worker.indexOf("const runTemplateLearning ="), "Incomplete receipt evidence must not be promoted as a successful template");
assert.match(worker, /const missingReceiptFields = effectiveImportMode === "receipt" && receiptDetails\s*\? incompleteReceiptFields/);
const route = readFileSync("app/api/imports/[importId]/process/route.ts", "utf8");
assert.match(route, /const needsReceiptConfirmation =\s*!result\.requiresInput &&/);
assert.match(readFileSync("components/import-files-modal.tsx", "utf8"), /const visualRepairGraceActive =\s*processingPhase !== "receipt_review_required"/);
assert.match(readFileSync("components/global-import-activity.tsx", "utf8"), /hasStructuredReceiptVisibility: Boolean\(payload\.receiptTransaction\)/);
const modelParser = readFileSync("lib/openai-import-parser.ts", "utf8");
assert.match(modelParser.slice(modelParser.indexOf("const buildOpenAIReceiptCoreSystemPrompt"), modelParser.indexOf("export const inferOpenAIDocumentFamily")), /RECEIPT_MONEY_GUIDANCE/);
assert.match(modelParser.slice(modelParser.indexOf("export const buildOpenAIBackupSystemPrompt"), modelParser.indexOf("const buildOpenAIReceiptCoreSystemPrompt")), /RECEIPT_MONEY_GUIDANCE/);
console.log("Incomplete receipt review: missing core fields, stopped retries, mobile/web messages and confirmed-data visibility passed.");
