import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { incompleteReceiptFields, receiptCurrencyForPersistence, receiptReviewMessage, RECEIPT_REVIEW_PHASE } from "../lib/receipt-review";
import { buildImportTelemetrySnapshot } from "../lib/import-telemetry";
import { resolveImportModalStatusDecision } from "../lib/import-modal-status";
import { mobileApiResponse } from "../lib/mobile-api-response";
import { enforceRegionalReceiptCurrencyEvidence, hasRegionalReceiptCurrencyEvidence } from "../lib/receipt-currency-evidence";

const complete = { merchant_raw: "상점", merchant_clean: null, transaction_date: "2026-09-30", currency: "KRW", total: 60000 };
assert.deepEqual(incompleteReceiptFields(complete), []);
assert.deepEqual(incompleteReceiptFields({ ...complete, merchant_raw: null, transaction_date: null, currency: null }), ["merchant", "date", "currency"]);
assert.deepEqual(incompleteReceiptFields({ ...complete, transaction_date: "2026-02-30" }), ["date"]);
assert.deepEqual(incompleteReceiptFields({ ...complete, total: NaN, currency: "MIXED" }), ["currency", "total"]);
assert.deepEqual(incompleteReceiptFields({ ...complete, total: 0 }), ["total"]);
assert.equal(receiptCurrencyForPersistence(null), "MIXED", "Do not assign PHP to an unknown receipt currency");
assert.equal(receiptCurrencyForPersistence("TL"), "MIXED", "A total label is not an ISO currency");
assert.equal(receiptCurrencyForPersistence("IDR"), "IDR");
assert.equal(receiptCurrencyForPersistence("KRW"), "KRW");
assert.equal(hasRegionalReceiptCurrencyEvidence("KRW", "회원 직원 합계 60,000"), false);
assert.equal(hasRegionalReceiptCurrencyEvidence("KRW", "정상과세판매가(3,120원)"), true);
assert.equal(hasRegionalReceiptCurrencyEvidence("KRW", "총 합계 157,600 원"), true);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "GRAND TOTAL 61,799 TUNAI 62,000"), false);
assert.equal(hasRegionalReceiptCurrencyEvidence("IDR", "Total Rp125.000"), true);
const inferred = { currency: "KRW", confidence_score: .98, parser_evidence: { reason: "Korean merchant", source_text: "합계 60,000" } };
assert.equal(enforceRegionalReceiptCurrencyEvidence(inferred).currency, null);
assert.equal(enforceRegionalReceiptCurrencyEvidence(inferred).confidence_score, .5);
assert.equal(inferred.currency, "KRW", "Keep original AI evidence unchanged for audit");
assert.equal(enforceRegionalReceiptCurrencyEvidence({ ...inferred, currency_source_text: "60,000원" }).currency, "KRW");
assert.deepEqual(incompleteReceiptFields({ ...complete, merchant_raw: " ", merchant_clean: "Toko", currency: "IDR" }), []);
const message = receiptReviewMessage(["date"]);
const snapshot = { status: "failed", processingPhase: RECEIPT_REVIEW_PHASE, processingMessage: message, workflowStage: "identifying_transactions", parsedRowsCount: 0, confirmedTransactionsCount: 0 };
const telemetry = buildImportTelemetrySnapshot(snapshot);
assert.equal(telemetry.canResume, false, "Missing source fields must not trigger repeated provider calls");
assert.equal(telemetry.phase, "repair_needed");
assert.equal(telemetry.message, message);
assert.equal(resolveImportModalStatusDecision({ ...snapshot, importMode: "receipt", telemetryPhase: telemetry.phase }).kind, "repair_needed");
assert.equal(resolveImportModalStatusDecision({ ...snapshot, importMode: "receipt", confirmedTransactionsCount: 1 }).kind, "visible", "Existing committed transactions retain visibility");
assert.equal(buildImportTelemetrySnapshot({ status: "processing", processingPhase: "queued_retry" }).canResume, true, "Transient failures remain recoverable");
const mobile = mobileApiResponse("import-status", { importFile: snapshot, confirmedTransactionsCount: 0, parsedRowsCount: 0, visibleImportComplete: false });
assert.equal((mobile.importFile as typeof snapshot).processingMessage, message);
assert.equal((mobile.importFile as typeof snapshot).status, "failed");
assert.equal(mobile.visibleImportComplete, false);
const worker = readFileSync("workers/import-processor.ts", "utf8");
assert.ok(worker.indexOf("const missingReceiptFields =") < worker.indexOf("const runTemplateLearning ="), "Incomplete receipt evidence must not be promoted as a successful template");
assert.match(worker, /effectiveImportMode === "receipt" && receiptDetails && rows\.length === 0/);
const route = readFileSync("app/api/imports/[importId]/process/route.ts", "utf8");
assert.match(route, /const needsReceiptConfirmation =\s*!result\.requiresInput &&/);
assert.match(readFileSync("components/import-files-modal.tsx", "utf8"), /const visualRepairGraceActive =\s*processingPhase !== "receipt_review_required"/);
assert.match(readFileSync("components/global-import-activity.tsx", "utf8"), /hasStructuredReceiptVisibility: Boolean\(payload\.receiptTransaction\)/);
const modelParser = readFileSync("lib/openai-import-parser.ts", "utf8");
assert.match(modelParser.slice(modelParser.indexOf("const buildOpenAIReceiptCoreSystemPrompt"), modelParser.indexOf("export const inferOpenAIDocumentFamily")), /RECEIPT_MONEY_GUIDANCE/);
assert.match(modelParser.slice(modelParser.indexOf("export const buildOpenAIBackupSystemPrompt"), modelParser.indexOf("const buildOpenAIReceiptCoreSystemPrompt")), /RECEIPT_MONEY_GUIDANCE/);
console.log("Incomplete receipt review: missing core fields, stopped retries, mobile/web messages and confirmed-data visibility passed.");
