import assert from 'node:assert/strict';
import { parseRecurringTracking, recurringPaymentAmount, recurringCompletionDate } from '../lib/recurring-tracking';
import { buildRecurringCalendarOccurrences } from '../lib/recurring-calendar';
import type { FinancialCommitmentSummary } from '../lib/commitments';
const tracking=parseRecurringTracking({version:1,totalPayments:12,paymentsMade:3,reminderDays:3})!;
const item={id:'fixture',title:'Laptop',kind:'reminder',status:'active',amount:'3000',currency:'PHP',dueDate:'2026-09-30',plannedPaymentDate:null,nextDueDate:'2026-09-30',recurrence:'monthly',tracking} as FinancialCommitmentSummary;
assert.equal(buildRecurringCalendarOccurrences([item],2026,8).length,1);
assert.equal(buildRecurringCalendarOccurrences([item],2027,4).length,1);
assert.equal(buildRecurringCalendarOccurrences([item],2027,5).length,0,'Nine remaining payments end in May.');
assert.throws(()=>parseRecurringTracking({version:1,totalPayments:12,paymentsMade:13}),/cannot exceed/);
assert.throws(()=>parseRecurringTracking({version:1,totalPayments:2.5}),/whole numbers/);
assert.throws(()=>parseRecurringTracking({version:1,paymentAmount:-1}),/non-negative/);
assert.throws(()=>parseRecurringTracking({version:1,reminderDays:9}),/supported/);
assert.equal(parseRecurringTracking(undefined),null,'Legacy schedules remain supported.');
assert.equal(recurringPaymentAmount({...item,kind:'debt',amount:'120000',tracking:{...tracking,paymentAmount:5000}}),5000,'Debt payment differs from outstanding balance.');
assert.equal(recurringPaymentAmount({...item,kind:'debt',tracking:{...tracking,paymentAmount:null}}),null,'Missing debt payment must not become the whole balance.');
assert.equal(buildRecurringCalendarOccurrences([{...item,tracking:{...tracking,totalPayments:null,endDate:'2026-09-30'}}],2026,9).length,0);
assert.equal(buildRecurringCalendarOccurrences([{...item,tracking:{...tracking,paymentsMade:12}}],2026,8).length,0);
assert.equal(buildRecurringCalendarOccurrences([{...item,dueDate:'2026-02-28',tracking:{...tracking,monthEnd:true}}],2026,2)[0].dateKey,'2026-03-31');
assert.equal(buildRecurringCalendarOccurrences([{...item,tracking:null}],2030,8).length,1,'Legacy cadence is unchanged.');
assert.equal(recurringPaymentAmount({...item,kind:'receivable',amount:'5000',dueDate:'2026-09-30',tracking:{...tracking,paymentAmount:2000}},'2026-11-30'),1000,'The last repayment cannot exceed the remaining balance.');
assert.equal(recurringCompletionDate({...item,dueDate:'2026-09-20',plannedPaymentDate:'2026-09-18'},'2026-10-18'),'2026-10-20');
assert.equal(recurringCompletionDate({...item,dueDate:'2026-01-31',plannedPaymentDate:'2026-01-29'},'2026-02-28'),'2026-02-28');
console.log('17 recurring tracking regressions passed.');
