import {useEffect,useState} from 'react';
import {View} from 'react-native';
import {Body,Button,Notice} from './ui';
import {useSession} from './session';
import type {BankLifecycleView} from '../../shared/finverse-lifecycle-view';
export function BankLifecyclePanel(){
 const session=useSession();const [revision,setRevision]=useState(0);const [data,setData]=useState<BankLifecycleView|null>(null),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();setData(null);setSelected([]);if(session.profileId&&!session.demo)void session.request<{lifecycle:BankLifecycleView}>(`finverse/connections?workspaceId=${encodeURIComponent(session.profileId)}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted){setData(d.lifecycle);setSelected(d.lifecycle.connections.flatMap(c=>c.accounts.filter(a=>a.retained&&!a.unlinkedAt&&c.status!=='disconnected'&&c.status!=='disconnect_pending').map(a=>a.id)));}}).catch(()=>{if(!c.signal.aborted)setMessage('Unable to load connected banks. Please retry.');});return()=>c.abort();},[session.profileId,session.demo,session.request,revision]);
 if(!data)return message?<View><Notice>{message}</Notice><Button title="Retry" onPress={()=>{setMessage('');setRevision(n=>n+1);}}/></View>:null;
 if(!data.connections.length)return null;
 const save=async()=>{setBusy(true);try{await session.request('finverse/connections',{method:'POST',body:JSON.stringify({workspaceId:session.profileId,retainIds:selected})});setMessage('Retained accounts saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}};
 return <View style={{gap:12}}><Body>Manage connected banks · {data.limit} allowed</Body><Body>Choose up to two to retain on Plus. Otherwise the most recently synced accounts are retained. Free disconnects all banks when paid access ends. History stays.</Body>{data.accessEndsAt?<Notice>Paid access ends {new Date(data.accessEndsAt).toLocaleDateString()}.</Notice>:null}<Body>After 90 days without a successful sync, connections disconnect with advance warnings. A shared bank login may need reconnection to keep only your chosen accounts.</Body>{data.connections.map(c=><View key={c.id} style={{gap:8}}><Body>{c.name} · {c.status==='disconnected'?'Disconnected':c.status==='disconnect_pending'?'Disconnection pending':'Connected'}</Body><Body>Last synced {c.lastSyncedAt?new Date(c.lastSyncedAt).toLocaleString():'Never'} · Inactivity deadline {new Date(c.inactivityDeadline).toLocaleDateString()}</Body>{c.disconnectError?<Notice>{c.disconnectError}</Notice>:null}{c.accounts.filter(a=>a.accountId).map(a=><Button key={a.id} secondary title={`${selected.includes(a.id)?'✓':'○'} ${a.name} · Keep on Plus`} disabled={busy||!!a.unlinkedAt||c.status==='disconnected'||c.status==='disconnect_pending'||(!selected.includes(a.id)&&selected.length>=2)} onPress={()=>setSelected(s=>s.includes(a.id)?s.filter(id=>id!==a.id):[...s,a.id])}/>)}</View>)}<Button secondary title="Save retained accounts" disabled={busy} onPress={()=>void save()}/>{message?<Notice>{message}</Notice>:null}</View>;
}
