import type { ImageSourcePropType } from "react-native";

export const mobileNavigationIcons: Record<string, ImageSourcePropType> = {
  "home-outline": require("../assets/icons/navigation/home.png"),
  "swap-horizontal-outline": require("../assets/icons/navigation/transactions.png"),
  "chatbubble-ellipses-outline": require("../assets/icons/navigation/adviser.png"),
  "person-outline": require("../assets/icons/navigation/profile.png"),
  "settings-outline": require("../assets/icons/navigation/settings.png"),
  "search-outline": require("../assets/icons/navigation/search.png"),
  "shield-checkmark-outline": require("../assets/icons/navigation/security.png"),
  "globe-outline": require("../assets/icons/navigation/region.png"),
  "desktop-outline": require("../assets/icons/navigation/display.png"),
  "server-outline": require("../assets/icons/navigation/data.png"),
  "people-outline": require("../assets/icons/navigation/profiles.png"),
  "card-outline": require("../assets/icons/navigation/plan.png"),
  "grid-outline": require("../assets/icons/navigation/categories.png"),
  "document-text-outline": require("../assets/icons/navigation/review.png"),
};
export const mobileInterfaceIcons: Record<string, ImageSourcePropType> = {
  "cloud-upload-outline": require("../assets/icons/interface/upload.png"),
  "cloud-download-outline": require("../assets/icons/interface/download.png"),
  "pencil-outline": require("../assets/icons/interface/edit.png"),
  "trash-outline": require("../assets/icons/interface/delete.png"),
  "close": require("../assets/icons/interface/close.png"),
  "close-outline": require("../assets/icons/interface/close.png"),
  "pause-outline": require("../assets/icons/interface/pause.png"),
  "play-outline": require("../assets/icons/interface/resume.png"),
  "refresh-outline": require("../assets/icons/interface/retry.png"),
  "arrow-undo-outline": require("../assets/icons/interface/undo.png"),
  "arrow-redo-outline": require("../assets/icons/interface/redo.png"),
  "calendar-outline": require("../assets/icons/interface/date.png"),
  "information-circle-outline": require("../assets/icons/interface/details.png"),
};
export const mobileCategoryIcons: Record<string, ImageSourcePropType> = {
  "income": require("../assets/icons/categories/income.png"),
  "food & dining": require("../assets/icons/categories/food-dining.png"),
  "transport": require("../assets/icons/categories/transport.png"),
  "housing": require("../assets/icons/categories/housing.png"),
  "bills & utilities": require("../assets/icons/categories/bills-utilities.png"),
  "travel & lifestyle": require("../assets/icons/categories/travel-lifestyle.png"),
  "entertainment": require("../assets/icons/categories/entertainment.png"),
  "shopping": require("../assets/icons/categories/shopping.png"),
  "subscriptions": require("../assets/icons/categories/subscriptions.png"),
  "health & wellness": require("../assets/icons/categories/health-wellness.png"),
  "education": require("../assets/icons/categories/education.png"),
  "financial": require("../assets/icons/categories/financial.png"),
  "cash & atm": require("../assets/icons/categories/cash-atm.png"),
  "gifts & donations": require("../assets/icons/categories/gifts-donations.png"),
  "business": require("../assets/icons/categories/business.png"),
  "transfers": require("../assets/icons/categories/transfers.png"),
  "other": require("../assets/icons/categories/other.png"),
  "groceries": require("../assets/icons/categories/groceries.png"),
  "medical": require("../assets/icons/categories/medical.png"),
  "salary": require("../assets/icons/categories/salary.png"),
  "investments": require("../assets/icons/categories/investments.png"),
  "uncategorized": require("../assets/icons/categories/uncategorized.png"),
  "children": require("../assets/icons/categories/children.png"),
  "utilities": require("../assets/icons/categories/bills-utilities.png"),
  "investment": require("../assets/icons/categories/investments.png"),
};
