import type { Bootstrap, Transaction } from "./types";
export const sampleBootstrap: Bootstrap = {
  firstName: "Alex",
  profiles: [{ id: "sample-personal", name: "Personal · sample" }],
  entitlement: {
    planTier: "free",
    accessEndsAt: null,
    renewing: false,
    nativePurchasesAvailable: false,
  },
};
export const sampleTransactions: Transaction[] = [
  [
    "groceries",
    "SM Supermarket",
    "-2480.50",
    "Groceries",
    "2026-09-05",
    "BPI Savings",
    "confirmed",
  ],
  [
    "coffee",
    "A neighbourhood café",
    "-185.00",
    "Dining",
    "2026-09-05",
    "GCash",
    "confirmed",
  ],
  [
    "ride",
    "Grab",
    "-220.00",
    "Transport",
    "2026-09-04",
    "GCash",
    "pending_review",
  ],
  [
    "bill",
    "Meralco",
    "-1920.00",
    "Utilities",
    "2026-09-03",
    "BPI Savings",
    "confirmed",
  ],
  [
    "salary",
    "September salary",
    "48000.00",
    "Salary",
    "2026-09-01",
    "BPI Savings",
    "confirmed",
  ],
  [
    "book",
    "Fully Booked",
    "-650.00",
    "Shopping",
    "2026-08-31",
    "BPI Savings",
    "confirmed",
  ],
].map(([id, name, amount, categoryName, date, accountName, reviewStatus]) => ({
  id,
  workspaceId: "sample-personal",
  accountId: accountName,
  accountName,
  date: `${date}T00:00:00.000Z`,
  amount,
  currency: "PHP",
  type: Number(amount) > 0 ? "income" : "expense",
  merchantRaw: name,
  merchantClean: name,
  description: null,
  categoryName,
  reviewStatus,
  tags: [],
}));
