import Link from "next/link";
import { JourneyHeader } from "@/app/landing-preview/landing-journey";
import { PublicFooter } from "@/components/public-footer";
import { SWITCH_TERM_ITEMS,SWITCH_PATH } from "../../../../shared/switch-campaign";
import { campaignConfig } from "@/lib/switch-campaign.server";
import { campaignOpen } from "../../../../shared/switch-campaign";
import { PostHogEvent } from "@/components/posthog-analytics";
import styles from "@/components/switch-campaign.module.css";
export const dynamic="force-dynamic";
export const metadata={title:"Switch to Clover | 30 days of Plus"};
export default async function Page(){const c=await campaignConfig();return <><JourneyHeader/><main className={`${styles.shell} ${styles.publicShell}`}><PostHogEvent event="campaign_progress" properties={{campaign_stage:"offer_viewed",campaign_id:"switch-to-clover"}}/><h1>Your finances, brought together.</h1><h2>Already paid for another budgeting app?</h2><p>Try Clover Plus free for 30 days. Bring your exported records and connect supported banks—all in one place.</p><section className={styles.card}><h2>Make room for your full picture</h2><ul><li>Export from your current app and upload a supported CSV, spreadsheet or statement. Review the imported results before confirming.</li><li>Connect up to two supported bank accounts. Availability varies by bank and country.</li><li>Use manual tracking, budgets, goals, Circles and your Plus AI allowance.</li></ul><p>No card required. No automatic renewal.</p></section><h2>How to claim</h2><ol><li>Create or sign in to your Free Clover account.</li><li>Submit a receipt screenshot or PDF for a paid budgeting or personal-finance app.</li><li>After approval, activate within seven days to start your 30 days.</li></ol><h2>Offer terms</h2><ul>{SWITCH_TERM_ITEMS.map(term=><li key={term}>{term}</li>)}</ul>{campaignOpen(c,new Date())?<Link href={SWITCH_PATH} className="button button-primary">Apply for the offer</Link>:<p>Applications are currently closed. Existing applicants can still <Link href={SWITCH_PATH}>view their application</Link>.</p>}<p><Link href="/sign-up?campaign=switch-to-clover">New to Clover? Create your account</Link></p></main><PublicFooter/></>;}
